### PR TITLE
Call `__set_name__` during setting type attribute.

### LINKED ISSUE #5523: [BUG] functools.cached_property does not work on cdef classes
### Describe the bug

The `cached_property` decorator fails when used inside a `cdef class`.

### Code to reproduce the behaviour:

```cython
from functools import cached_property
cdef class A:
    @cached_property
    def x(self):
        return 1

a = A()
a.x
```

Output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
----> 1 a.x

File ...
    963     return self
    964 if self.attrname is None:
--> 965     raise TypeError(
    966         "Cannot use cached_property instance without calling __set_name__ on it.")
    967 try:
    968     cache = instance.__dict__

TypeError: Cannot use cached_property instance without calling __set_name__ on it.
```

### Expected behaviour

The above snippet should generate a working (cached) property.

According to the docs, [`__set_name__` is only called on descriptors if they are created as part of the class definition](https://docs.python.org/3/reference/datamodel.html#object.__set_name__). I suspect that the reason for this issue is that Cython is actually translating the above code into the equivalent of 
```python
from functools import cached_property
class A:
    def x(self):
        return 1

A.x = cached_property(A.x)

a = A()
a.x
```
which reproduces the issue in pure Python. The above snippet may be fixed by manually calling `A.x.__set_name__(A, "x")`, so I would guess that line needs to be added into the Cython handling of the cached property as well somewhere. 

### OS

Linux

### Python version

3.8.16 (and 3.10.2)

### Cython version

3.0.0b3 (and 0.29.36)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by matusvalo**
Based on https://docs.python.org/3/reference/datamodel.html#object.__set_name__

Fixes #5523

### CODE REVIEW

File: Cython/Utility/ExtensionTypes.c [hunk 1]
```diff
@@ -663,7 +663,12 @@ static int __Pyx__SetItemOnTypeDict(PyTypeObject *tp, PyObject *k, PyObject *v)
 #else
     result = PyDict_SetItem(tp->tp_dict, k, v);
 #endif
-    if (likely(!result)) PyType_Modified(tp);
+    if (likely(!result)) {
+        PyType_Modified(tp);
+        if (PyObject_HasAttrString(v, "__set_name__")) {
+            PyObject_CallMethod(v, "__set_name__", "OO", (PyObject *) tp, k);
```
Comment (matusvalo) [inline Cython/Utility/ExtensionTypes.c:669]: Here we need to check and manage returned value.

**Comment by matusvalo** [comment]
For now marked as draft for early feedback. This is test proving PR fix:

```cython
from functools import cached_property

cdef class A:
    cdef dict __dict__

    @cached_property
    def x(self):
        return 1

a = A()
a.x
```

File: Cython/Utility/ExtensionTypes.c (hunk 1 above)
Comment (da-woods) [reply Cython/Utility/ExtensionTypes.c:669]: Yes - that's fairly straightforward I think. Just

```
setNameResult = PyObject_Callmethod(...);
if (!setNameResult) return -1;
Py_DECREF(setNameResult);
```

Comment (da-woods) [inline Cython/Utility/ExtensionTypes.c:669]:
```suggestion
        if (PyObject_HasAttr(v, PYIDENT("__set_name__"))) {
            PyObject_CallMethodObjArgs(v, PYIDENT("__set_name__"),  (PyObject *) tp, k, NULL);
```

Fairly minor, but I think this should be slightly faster - partly because it only creates the `"__set_name__"` string once at module startup and partly because the function call should be quicker.

(`PYIDENT` is a Cython trick when processing utility code to substitute out reused strings).

With that said, this isn't really performance sensitive so doesn't matter too much.

**Review by da-woods — COMMENTED** [review]
Needs handling of the result, but otherwise looks reasonable.

I think that's a sensible place to put the call.

I agree it seems worth doing this for cdef classes.

File: Cython/Utility/ExtensionTypes.c (hunk 1 above)
Comment (matusvalo) [reply Cython/Utility/ExtensionTypes.c:669]: Thank you @da-woods. I am not expert in C API so any advice is highly appreciated.

File: Cython/Utility/ExtensionTypes.c [hunk 2]
```diff
@@ -655,6 +655,7 @@ static int __Pyx__SetItemOnTypeDict(PyTypeObject *tp, PyObject *k, PyObject *v);
 
 static int __Pyx__SetItemOnTypeDict(PyTypeObject *tp, PyObject *k, PyObject *v) {
     int result;
+    PyObject *setNameResult;
```
Comment (scoder) [inline Cython/Utility/ExtensionTypes.c:658]: It's enough to declare this locally where it's needed. That avoids reasoning about dangling pointers when reading the code.
```suggestion
```

File: Cython/Utility/ExtensionTypes.c [hunk 3]
```diff
@@ -663,7 +664,14 @@ static int __Pyx__SetItemOnTypeDict(PyTypeObject *tp, PyObject *k, PyObject *v)
 #else
     result = PyDict_SetItem(tp->tp_dict, k, v);
 #endif
-    if (likely(!result)) PyType_Modified(tp);
+    if (likely(!result)) {
+        PyType_Modified(tp);
+        if (unlikely(PyObject_HasAttr(v, PYIDENT("__set_name__")))) {
+            setNameResult = PyObject_CallMethodObjArgs(v, PYIDENT("__set_name__"),  (PyObject *) tp, k, NULL);
```
Comment (scoder) [inline Cython/Utility/ExtensionTypes.c:670]:
```suggestion
            PyObject *setNameResult = PyObject_CallMethodObjArgs(v, PYIDENT("__set_name__"),  (PyObject *) tp, k, NULL);
```

**Review by scoder — APPROVED** [review]
