### PR TITLE
Replace tuple and list pack with "FromArray"

### LINKED ISSUE #7258: Replace `PyTuple_Pack` (and our list equivalent) with PyTuple_FromArray
### Describe your issue

We mostly use `PyTuple_Pack` and `__Pyx_PyList_Pack` in the module initialization code. In this case we're prioritizing code-size over speed by not manually unrolling the loop to `PyTuple_New(...); PyTuple_SetItem(0, item0); PyTuple_SetItem(1, item1)`.

It's been claimed (but I can't find the exact numbers right now) that C varargs don't have the best performance and passing arrays around is a little quicker. Python 3.15 adds `PyTuple_FromArray` for this reason but we already have our own versions.

My second reason for wanting to do this that MSVC+ARM has a compiler bug where it passes the wrong arguments for sufficiently large varargs functions. Obviously MSVC should fix that and we shouldn't have to work around it. But the workaround is probably an improvement anyway.

Change is:

```
some_temp = PyTuple_Pack(3, temp0, temp1, temp2);
```

to

```
{
    PyObject *temp_args[] = {temp0, temp1, temp2};
    some_temp = PyTuple_FromArray(temp_args, 3);
}
```

### PR DESCRIPTION
**Pull request by da-woods**
Closes #7258

The main reason to do this is to avoid going through a C varargs call which typically isn't hugely efficient. We mostly use these in module setup code (where performance isn't a huge issue) so possibly this isn't a huge worry. But there's probably little reason not to.

A secondary reason is that it avoids an MSVC+ARM compiler bug when creating large tuples and list.

Note that I haven't replaced PyTuple_Pack outside of module setup code.

(There's maybe also a question if this makes the Limited API slightly worse in that `PyTuple_Pack` can use the quick internal `SET_ITEM` macros, while our version has to use the slower checked functions)

### CODE REVIEW

File: Cython/Utility/ObjectHandling.c [hunk 1]
```diff
@@ -917,34 +903,53 @@ static CYTHON_INLINE void __Pyx_copy_object_array(PyObject *const *CYTHON_RESTRI
...
+#endif
 
+/////////////// TupleOrListFromArrayImpl.proto //////////////
+
+{{if Type == 'Tuple'}}
+#if PY_VERSION_HEX >= 0x030F0000 && !CYTHON_COMPILING_IN_LIMITED_API
+#define __Pyx_PyTuple_FromArray PyTuple_FromArray
+#else
+{{endif}}
 static CYTHON_INLINE PyObject *
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c]: If the intention is to reduce code overhead in init functions, then we'd better not request inlining.
(EDIT: Although those are specifically marked to produce "small code", so the end result should be the same. Still, in the current usages, we don' _intend_ them to be inlined.)

**Review by scoder — APPROVED** [review]
Looks good to me, just one comment.

**Comment by da-woods** [comment]
For reference, it looks like this typically makes extensions slightly larger. That's probably expected because it adds a couple of new functions (on Python <3.15). It's not by an amount that I think it worth worrying about.
