### PR TITLE
Fixes #4143: Can't catch ValueError from float() calls

### LINKED ISSUE #4143: Can't catch ValueError from float() calls
In latest master branch, it seems this pattern fails when given a string that can't be converted to a float:

```
def foo(val):
    try:
        a = float(val)
    except ValueError:
        a = val

    return a
```

Compiling and running this gets this error:
```
$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython_trycatch
>>> cython_trycatch.foo("foo")
ValueError: could not convert string to float: 'foo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <cyfunction foo at 0x7f86475a0930> returned a result with an error set
>>> 
```

This problem isn't present on the latest release 0.29.23. I bisected the cython repo and found the commit 337bf7f3b6611126c86cc55de9112eafa2e34034 introduced this problem.

Unfortunately I don't quite know enough about cython internals to fix this myself. Hope this helps, and thanks for the great project!

### PR DESCRIPTION
**Pull request by brownan**
See issue #4143 

The implementation of __Pyx__PyNumber_Float() wasn't checking whether errors occurred on the calls to __Pyx_PyUnicode_AsDouble(), __Pyx_PyBites_AsDouble(), and __Pyx_PyByteArray_AsDouble(). Errors from those functions are now properly propagated to the caller.

I didn't understand the `@cython.test_assert_path_exists` decorators on some of the tests in that file. Please let me know if this new test needs such a decorator.

### CODE REVIEW

**Comment by TeamSpen210** [comment]
Those are documented in the [hacker guide](https://github.com/cython/cython/wiki/HackerGuide#parse-tree-assertions), and allow you to assert that particular parse tree nodes do or don't exist in the code. They're mainly used to check that optimisations have actually been applied, and that the generic Python operations aren't used.

File: Cython/Utility/TypeConversion.c [hunk 1]
```diff
@@ -475,12 +475,16 @@ static CYTHON_INLINE PyObject* __Pyx__PyNumber_Float(PyObject* obj); /* proto */
 
 static CYTHON_INLINE PyObject* __Pyx__PyNumber_Float(PyObject* obj) {
     // obj is PyFloat is handled in the calling macro
+    double val;
     if (PyUnicode_CheckExact(obj)) {
-        return PyFloat_FromDouble(__Pyx_PyUnicode_AsDouble(obj));
+        val = __Pyx_PyUnicode_AsDouble(obj);
+        return val == -1 && PyErr_Occurred() ? NULL : PyFloat_FromDouble(val);
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:481]:
```suggestion
        return unlikely(val == -1 && PyErr_Occurred()) ? NULL : PyFloat_FromDouble(val);
```

File: Cython/Utility/TypeConversion.c [hunk 2]
```diff
@@ -475,12 +475,16 @@ static CYTHON_INLINE PyObject* __Pyx__PyNumber_Float(PyObject* obj); /* proto */
...
     } else if (PyBytes_CheckExact(obj)) {
-        return PyFloat_FromDouble(__Pyx_PyBytes_AsDouble(obj));
+        val = __Pyx_PyBytes_AsDouble(obj);
+        return val == -1 && PyErr_Occurred() ? NULL : PyFloat_FromDouble(val);
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:484]:
```suggestion
        return unlikely(val == -1 && PyErr_Occurred()) ? NULL : PyFloat_FromDouble(val);
```

File: Cython/Utility/TypeConversion.c [hunk 3]
```diff
@@ -475,12 +475,16 @@ static CYTHON_INLINE PyObject* __Pyx__PyNumber_Float(PyObject* obj); /* proto */
...
     } else if (PyByteArray_CheckExact(obj)) {
-        return PyFloat_FromDouble(__Pyx_PyByteArray_AsDouble(obj));
+        val = __Pyx_PyByteArray_AsDouble(obj);
+        return val == -1 && PyErr_Occurred() ? NULL : PyFloat_FromDouble(val);
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:487]:
```suggestion
        return unlikely(val == -1 && PyErr_Occurred()) ? NULL : PyFloat_FromDouble(val);
```

**Review by scoder — COMMENTED** [review]
Good catch. I'll just let the C compiler know what case it should optimise for.

**Comment by scoder** [comment]
Thanks
