### PR TITLE
Stop users from creating Cython shared types

### LINKED ISSUE #7263: [BUG] Abort from calling `repr(cyfunction.__class__())`
### Describe the bug

Calling `repr(cyfunction.__class__())` in a debug build leads to an abort.

Here's the backtrace, implicating `__Pyx_CyFunction_repr `:

```
python: Objects/unicodeobject.c:3047: unicode_fromformat_arg: Assertion `obj && _PyUnicode_CHECK(obj)' failed.

Program received signal SIGABRT, Aborted.

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737340064384) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737340064384) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737340064384, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff72f7476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72dd7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff72dd71b in __assert_fail_base (fmt=0x7ffff7492130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x555556291520 "obj && _PyUnicode_CHECK(obj)", file=0x555556287ec0 "Objects/unicodeobject.c", line=3047, function=<optimized out>)
    at ./assert/assert.c:94
#6  0x00007ffff72eee96 in __GI___assert_fail (assertion=assertion@entry=0x555556291520 "obj && _PyUnicode_CHECK(obj)",
    file=file@entry=0x555556287ec0 "Objects/unicodeobject.c", line=line@entry=3047,
    function=function@entry=0x555556296c20 <__PRETTY_FUNCTION__.247> "unicode_fromformat_arg") at ./assert/assert.c:103
#7  0x0000555555c5e82b in unicode_fromformat_arg (writer=writer@entry=0x7fffffffc480, f=0x7ffff42d260d "U at %p>",
    f@entry=0x7ffff42d260c "%U at %p>", vargs=vargs@entry=0x7fffffffc3b0) at Objects/unicodeobject.c:3047
#8  0x0000555555c5f22f in unicode_from_format (writer=writer@entry=0x7fffffffc480, format=format@entry=0x7ffff42d2600 "<cyfunction %U at %p>",
    vargs=vargs@entry=0x7fffffffc560) at Objects/unicodeobject.c:3223
#9  0x0000555555c5f5e1 in PyUnicode_FromFormatV (format=format@entry=0x7ffff42d2600 "<cyfunction %U at %p>", vargs=vargs@entry=0x7fffffffc560)
    at Objects/unicodeobject.c:3257
#10 0x0000555555c5f78a in PyUnicode_FromFormat (format=format@entry=0x7ffff42d2600 "<cyfunction %U at %p>") at Objects/unicodeobject.c:3271
#11 0x00007ffff42b9455 in __Pyx_CyFunction_repr (op=0x7fffb26dd830) at src/pyhacl/signature/ed25519.c:6223
#12 0x0000555555b00f57 in PyObject_Repr (v=0x7fffb26dd830) at Objects/object.c:779
#13 0x0000555555d604f9 in builtin_repr (module=<optimized out>, obj=<optimized out>) at Python/bltinmodule.c:2576
#14 0x0000555555aefd1e in cfunction_vectorcall_O (func=0x7fffb23b19e0, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/methodobject.c:536
#15 0x00005555559aa093 in _PyObject_VectorcallTstate (tstate=0x5555567c3a40 <_PyRuntime+362752>, callable=0x7fffb23b19e0, args=0x7fffffffcdf8,
    nargsf=9223372036854775809, kwnames=0x0) at ./Include/internal/pycore_call.h:169
#16 0x00005555559aa1ee in PyObject_Vectorcall (callable=callable@entry=0x7fffb23b19e0, args=args@entry=0x7fffffffcdf8, nargsf=<optimized out>,
    kwnames=kwnames@entry=0x0) at Objects/call.c:327
```

### Code to reproduce the behaviour:

crash_cython2.py:
```python
def f(): pass
```

```python
>>> import crash_cython2
>>> crash_cython2.f
<cyfunction f at 0x7ff8b30624d0>
>>> crash_cython2.f()
>>> crash_cython2.f.__class__
<class '_cython_3_1_6.cython_function_or_method'>
>>> repr(crash_cython2.f.__class__())
python: Objects/unicodeobject.c:3047: unicode_fromformat_arg: Assertion `obj && _PyUnicode_CHECK(obj)' failed.
Aborted (core dumped)
```

### Expected behaviour

No abort.

### OS

Linux

### Python version

Python 3.14.0+ free-threading build (heads/3.14:853e5d94eb6, Oct 22 2025, 20:11:47) [GCC 11.4.0]

### Cython version

3.1.6

### Additional context

I haven't tested on a non-debug build, nor with Cython latest master branch.

Original report: https://codeberg.org/drlazor8/pyhacl/issues/3

Found using [fusil](https://github.com/devdanzin/fusil), by @vstinner.

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #7263

### CODE REVIEW

File: Cython/Utility/AsyncGen.c [hunk 1]
```diff
@@ -416,8 +416,8 @@ static PyType_Spec __pyx_AsyncGenType_spec = {
     __PYX_TYPE_MODULE_PREFIX "async_generator",
     sizeof(__pyx_PyAsyncGenObject),
     0,
-#if PY_VERSION_HEX >= 0x030A0000
-    Py_TPFLAGS_IMMUTABLETYPE |
+#if __PYX_LIMITED_VERSION_HEX >= 0x030A0000
+    Py_TPFLAGS_IMMUTABLETYPE | Py_TPFLAGS_DISALLOW_INSTANTIATION |
```
Comment (scoder) [inline Cython/Utility/AsyncGen.c]: Hmm, but this means that we won't set the flag in the abi3 wheels. I think we need to define both flags ourselves if they are not defined yet.

Comment (da-woods) [reply Cython/Utility/AsyncGen.c]: For "Py_TPFLAGS_DISALLOW_INSTANTIATION" that's OK - it's covered by `__pyx_CommonTypesMetaclass_call` (although you can still instantiate the metaclass, but it has no state so it doesn't really matter).

For `Py_TPFLAGS_IMMUTABLETYPE` that's true.

File: Cython/Utility/CommonStructures.c [hunk 2]
```diff
@@ -173,21 +173,38 @@ static PyObject* __pyx_CommonTypesMetaclass_get_module(CYTHON_UNUSED PyObject *s
...
+static PyObject* __pyx_CommonTypesMetaclass_call(CYTHON_UNUSED PyObject *self, CYTHON_UNUSED PyObject *args, CYTHON_UNUSED PyObject *kwds) {
+    PyErr_SetString(PyExc_TypeError, "Cannot instantiate Cython shared types");
+    return NULL;
+}
+
+static PyObject* __pyx_CommonTypesMetaclass_setattr(CYTHON_UNUSED PyObject *self, CYTHON_UNUSED PyObject *attr, CYTHON_UNUSED PyObject *value) {
+    PyErr_SetString(PyExc_TypeError, "Cython shared types are immutable");
+    return NULL;
+}
+#endif
```
Comment (scoder) [inline Cython/Utility/CommonStructures.c:186]: I'm not sure "shared" is clear here. Maybe "Cython internal types"?

File: Cython/Utility/AsyncGen.c (hunk 1 above)
Comment (da-woods) [reply Cython/Utility/AsyncGen.c]: I've defined `tp_setattro` for the metatype to enforce immutability if we don't have the flags.

**Review by scoder — APPROVED** [review]

**Comment by da-woods** [comment]
3.1.x commit 3a8e5ce95
