### PR TITLE
More robust Limited API SetItemOnTypeDict

### LINKED ISSUE #6323: [BUG] Cython uses PyObject_GenericSetAttr() on types in Limited API
### Describe the bug

This code now hits an assertion in dev-builds of the CPython main branch:
https://github.com/cython/cython/blob/7e8a172d21b0c723be14685e25ae854bbc6cdaec/Cython/Utility/ExtensionTypes.c#L694-L699

https://github.com/python/cpython/blob/e6fad7a0e3d824f4a3c9cd71a48208880606d705/Objects/object.c#L1714
```c
    assert(!PyType_IsSubtype(tp, &PyType_Type));
```

This is used in the auto-reduce setup code to fix up the reduce methods after creating the type. The assertion was added in
https://github.com/python/cpython/pull/118454

Not sure if there's a way to work around this – or whether we should. It seems to be a hack on our side to update the type dict like this (even *after* adding the type to the module dict).

### Code to reproduce the behaviour:

_No response_

### Expected behaviour

_No response_

### OS

_No response_

### Python version

3.14

### Cython version

master

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
Instead of relying of PyObject_GenericSetAttr (which looks to have been updated in Python 3.14 to ban this usage) we instead work out where the type dict is from `__dictoffset__` and manipulate that.

Fixes #6323

### CODE REVIEW

File: Cython/Utility/ExtensionTypes.c [hunk 1]
```diff
@@ -681,7 +681,46 @@ static int __Pyx_call_type_traverse(PyObject *o, int always_call, visitproc visi
...
+            tp_dictoffset = 0; // try again next time
+            return -1;
+        }
+    }
+    return tp_dictoffset;
+}
+
+static PyObject *__Pyx_GetTypeDict(PyTypeObject *tp) {
+    Py_ssize_t tp_dictoffset = __Pyx_GetTypeDictOffset();
+    if (unlikely(tp_dictoffset == -1 && PyErr_Occurred())) return NULL;
```
Comment (scoder) [inline Cython/Utility/ExtensionTypes.c:717]: `type.__dictoffset__` is not writable, so it seems a fatal error if `tp_dictoffset < 0` and no exception was raised. That should never happen.
```suggestion
    if (unlikely(tp_dictoffset == -1)) {
        assert(PyErr_Occurred());
        return NULL;
    }
```

**Review by scoder — COMMENTED** [review]
That's a smart implementation. Nice.

File: Cython/Utility/ExtensionTypes.c (hunk 1 above)
Comment (da-woods) [reply Cython/Utility/ExtensionTypes.c:717]: tp_dictoffset can definitely be negative (and I think always is for `Py_TPFLAGS_MANAGED_DICT`) - the negative value doesn't have a special meaning except that the dict pointer is infront of the object.

On Python 3.11:

```
>>> class C:
...   pass
... 
>>> C.__dictoffset__
-48
>>> 
```

I suspect `-1` is very unlikely because it implies 1 byte pointers. But it isn't obvious that it's always forbidden so I'd rather leave this bit as is.

Comment (da-woods) [reply Cython/Utility/ExtensionTypes.c:717]: This doesn't look to be completely right... negative offset indicates the offset is from the end of the object instead of the start.

File: Cython/Utility/ExtensionTypes.c [hunk 2]
```diff
@@ -681,7 +681,46 @@ static int __Pyx_call_type_traverse(PyObject *o, int always_call, visitproc visi
...
+// once we're done (pending C API support for this).
+static PyObject *__Pyx_GetTypeDict(PyTypeObject *tp); /* proto */
+#endif
+
+////////////////// LimitedApiGetTypeDict //////////////////////
+
+#if CYTHON_COMPILING_IN_LIMITED_API
+static Py_ssize_t __Pyx_GetTypeDictOffset(void) {
+    // TODO - if we ever support custom metatypes for extension types then
+    // we have to drop this caching.
```
[the remark this answers is not in the document]
Comment (da-woods) [reply Cython/Utility/ExtensionTypes.c]: I've just changed the comment here for now.

That'd work as a solution, but doesn't seem worth implementing until we need it.

File: Cython/Utility/ExtensionTypes.c [hunk 3]
```diff
@@ -681,7 +681,46 @@ static int __Pyx_call_type_traverse(PyObject *o, int always_call, visitproc visi
...
+    static Py_ssize_t tp_dictoffset = 0;
+    if (tp_dictoffset == 0) {
+        PyObject *tp_dictoffset_o = NULL;
+        tp_dictoffset_o = PyObject_GetAttrString((PyObject*)(&PyType_Type), "__dictoffset__");
+        if (unlikely(!tp_dictoffset_o)) return -1;
+        tp_dictoffset = PyLong_AsSsize_t(tp_dictoffset_o);
+        if (unlikely(tp_dictoffset == -1 && PyErr_Occurred())) {
+            tp_dictoffset = 0; // try again next time
+            return -1;
+        }
```
[the remark this answers is not in the document]
Comment (da-woods) [reply Cython/Utility/ExtensionTypes.c]: Done

File: Cython/Utility/ExtensionTypes.c [hunk 4]
```diff
@@ -681,7 +681,67 @@ static int __Pyx_call_type_traverse(PyObject *o, int always_call, visitproc visi
...
+        // negative, but isn't in Python <=3.13 (current at time
+        // of writing).  It's awkward to calculate in the limited 
+        // API because we need to know the object size.  For now
+        // just raise an error and fix it if it every changes.
+        PyErr_SetString(
+            PyExc_TypeError,
+            "'type' has an unexpected negative dictoffset. "
+            "Report this as Cython bug");
+        return NULL;
+    }
```
Comment (scoder) [inline Cython/Utility/ExtensionTypes.c:738]: I think this whole error reporting code can go into `__Pyx_GetTypeDictOffset()` as well. Once the offset variable is initialised, this code should never be touched again and can completely go out of the way.
