### PR TITLE
Fix handling of cpp_locals exception in nogil

### LINKED ISSUE #6834: [BUG] __Pyx_RaiseCppAttributeError does not acquire the GIL
### Describe your issue

This affects the cpp_locals directive. Something like

```
from libcpp.string cimport string

@cython.cpp_locals
def f():
    cdef string s
    with nogil:
        return s=="123" 
```

will cause a segmentation fault (when it should raise an exception). Current master and probably current 3.0 branch.

### PR DESCRIPTION
**Pull request by da-woods**
We need to reacquire the GIL in this case (which we mostly didn't do before because it was just dealing with Python objects which always had the GIL)

Fixes #6834

Should probably wait until after 3.1 - it's a fairly niche issue (and not a regression)

### CODE REVIEW

File: Cython/Utility/ObjectHandling.c [hunk 1]
```diff
@@ -3239,17 +3252,15 @@ static CYTHON_INLINE void __Pyx_RaiseClosureNameError(const char *varname) {
...
-static void __Pyx_RaiseUnboundMemoryviewSliceNogil(const char *varname);/*proto*/
-
-/////////////// RaiseUnboundMemoryviewSliceNogil ///////////////
-//@requires: RaiseUnboundLocalError
+/////////////// RaiseClosureNameErrorNogil ///////////////
+//@requires: RaiseClosureNameError
 
-// Don't inline the function, it should really never be called in production
-static void __Pyx_RaiseUnboundMemoryviewSliceNogil(const char *varname) {
+static CYTHON_INLINE void __Pyx_RaiseClosureNameErrorNogil(const char *varname) {
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c:3261]: What makes this special enough for inlining?

**Review by scoder — COMMENTED** [review]
Seems fine, just style comments.

File: Cython/Compiler/Code.py [hunk 2]
```diff
@@ -2961,28 +2961,25 @@ def put_error_if_neg(self, pos, value):
...
+        nogil_tag = "Nogil" if in_nogil_context else ""
         if entry.from_closure:
-            func = '__Pyx_RaiseClosureNameError'
+            func = f'__Pyx_RaiseClosureNameError{nogil_tag}'
             self.globalstate.use_utility_code(
-                UtilityCode.load_cached("RaiseClosureNameError", "ObjectHandling.c"))
-        elif entry.type.is_memoryviewslice and in_nogil_context:
-            func = '__Pyx_RaiseUnboundMemoryviewSliceNogil'
-            self.globalstate.use_utility_code(
-                UtilityCode.load_cached("RaiseUnboundMemoryviewSliceNogil", "ObjectHandling.c"))
```
Comment (scoder) [inline Cython/Compiler/Code.py:2971]: Why is this section gone?

File: Cython/Utility/ObjectHandling.c (hunk 1 above)
Comment (da-woods) [reply Cython/Utility/ObjectHandling.c:3261]: Yeah was a copy-paste mistake on this one. But I agree - I'll remove it from the inner layer too.

**Comment by scoder** [comment]
Looks good to me. Can go in.
