### PR TITLE
Move Py_UNICODE out of universal utility code

### LINKED ISSUE #5982: [BUG] `Py_UNICODE` is deprecated Python 3.13
### Describe the bug

While compiling using `3.13.0a3` getting error:

``` bash
Compiling src/liburing/file.pyx because it changed.
Compiling src/liburing/helper.pyx because it changed.                                                 
Compiling src/liburing/io_uring.pyx because it changed.    
Compiling src/liburing/liburing.pyx because it changed.
Compiling src/liburing/type.pyx because it changed.
Compiling src/liburing/version.pyx because it changed.                                               
[1/6] Cythonizing src/liburing/file.pyx
[2/6] Cythonizing src/liburing/helper.pyx                                                            
[3/6] Cythonizing src/liburing/io_uring.pyx                                                          
[4/6] Cythonizing src/liburing/liburing.pyx                                                          
[5/6] Cythonizing src/liburing/type.pyx                                                              
[6/6] Cythonizing src/liburing/version.pyx                                                           
running build_ext
building 'liburing.file' extension                                                                    
building 'liburing.helper' extension
creating build                            
creating build
creating build/temp.linux-x86_64-cpython-313
creating build/temp.linux-x86_64-cpython-313
building 'liburing.io_uring' extension
building 'liburing.liburing' extension
creating build/temp.linux-x86_64-cpython-313/src
building 'liburing.type' extension
creating build/temp.linux-x86_64-cpython-313/src
creating build/temp.linux-x86_64-cpython-313/src
building 'liburing.version' extension
creating build/temp.linux-x86_64-cpython-313/src/liburing
creating build/temp.linux-x86_64-cpython-313/src/liburing
creating build/temp.linux-x86_64-cpython-313/src/liburing
creating build/temp.linux-x86_64-cpython-313/src/liburing
creating build/temp.linux-x86_64-cpython-313/src/liburing
creating build/temp.linux-x86_64-cpython-313/src/liburing
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=1 -Ilibs/liburing/src/include -I/opt/python/3.13/include/python3.13 -c src/liburing/io_uring.c -o build/temp.linux-x86_64-cpython-313/src/liburing/io_uring.o -Og
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=1 -Ilibs/liburing/src/include -I/opt/python/3.13/include/python3.13 -c src/liburing/type.c -o build/temp.linux-x86_64-cpython-313/src/liburing/type.o -Og
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=1 -Ilibs/liburing/src/include -I/opt/python/3.13/include/python3.13 -c src/liburing/helper.c -o build/temp.linux-x86_64-cpython-313/src/liburing/helper.o -Og
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=1 -Ilibs/liburing/src/include -I/opt/python/3.13/include/python3.13 -c src/liburing/file.c -o build/temp.linux-x86_64-cpython-313/src/liburing/file.o -Og
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=1 -Ilibs/liburing/src/include -I/opt/python/3.13/include/python3.13 -c src/liburing/liburing.c -o build/temp.linux-x86_64-cpython-313/src/liburing/liburing.o -Og
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=1 -Ilibs/liburing/src/include -I/opt/python/3.13/include/python3.13 -c src/liburing/version.c -o build/temp.linux-x86_64-cpython-313/src/liburing/version.o -Og
src/liburing/helper.c:1308:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]         
 1308 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)                      
      | ^~~~~~                                                                                        
src/liburing/helper.c: In function ‘__Pyx_Py_UNICODE_strlen’:                                         
src/liburing/helper.c:1310:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]         
 1310 |     const Py_UNICODE *u_end = u;                                                              
      |     ^~~~~                                                                                     
src/liburing/type.c:1322:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]           
 1322 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)                      
      | ^~~~~~                                                                                        
src/liburing/type.c: In function ‘__Pyx_Py_UNICODE_strlen’:                                           
src/liburing/type.c:1324:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]           
 1324 |     const Py_UNICODE *u_end = u;                                                              
      |     ^~~~~                                                                                     
src/liburing/io_uring.c:1324:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]       
 1324 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)                      
      | ^~~~~~                                                                                        
src/liburing/io_uring.c: In function ‘__Pyx_Py_UNICODE_strlen’:                                       
src/liburing/io_uring.c:1326:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]       
 1326 |     const Py_UNICODE *u_end = u;                                                              
      |     ^~~~~                                                                                     
src/liburing/version.c:1321:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]        
 1321 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)                      
      | ^~~~~~                                                                                        
src/liburing/version.c: In function ‘__Pyx_Py_UNICODE_strlen’:                                        
src/liburing/version.c:1323:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]        
 1323 |     const Py_UNICODE *u_end = u;                                                              
      |     ^~~~~                                                                                     
src/liburing/file.c:1324:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]           
 1324 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)                      
      | ^~~~~~                                                                                        
src/liburing/file.c: In function ‘__Pyx_Py_UNICODE_strlen’:                                           
src/liburing/file.c:1326:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]           
 1326 |     const Py_UNICODE *u_end = u;                                                              
      |     ^~~~~                                                                                     
src/liburing/liburing.c:1325:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]       
 1325 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)                      
      | ^~~~~~                                                                                        
src/liburing/liburing.c: In function ‘__Pyx_Py_UNICODE_strlen’:                                       
src/liburing/liburing.c:1327:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]       
 1327 |     const Py_UNICODE *u_end = u;                                                              
      |     ^~~~~                                                                                     
creating build/lib.linux-x86_64-cpython-313
creating build/lib.linux-x86_64-cpython-313/liburing
gcc -shared build/temp.linux-x86_64-cpython-313/src/liburing/version.o -Llibs/liburing/src -luring -o build/lib.linux-x86_64-cpython-313/liburing/version.cpython-313-x86_64-linux-gnu.so
gcc -shared build/temp.linux-x86_64-cpython-313/src/liburing/helper.o -Llibs/liburing/src -luring -o build/lib.linux-x86_64-cpython-313/liburing/helper.cpython-313-x86_64-linux-gnu.so
gcc -shared build/temp.linux-x86_64-cpython-313/src/liburing/file.o -Llibs/liburing/src -luring -o build/lib.linux-x86_64-cpython-313/liburing/file.cpython-313-x86_64-linux-gnu.so
gcc -shared build/temp.linux-x86_64-cpython-313/src/liburing/liburing.o -Llibs/liburing/src -luring -o build/lib.linux-x86_64-cpython-313/liburing/liburing.cpython-313-x86_64-linux-gnu.so
gcc -shared build/temp.linux-x86_64-cpython-313/src/liburing/type.o -Llibs/liburing/src -luring -o build/lib.linux-x86_64-cpython-313/liburing/type.cpython-313-x86_64-linux-gnu.so
gcc -shared build/temp.linux-x86_64-cpython-313/src/liburing/io_uring.o -Llibs/liburing/src -luring -o build/lib.linux-x86_64-cpython-313/liburing/io_uring.cpython-313-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-313/liburing/file.cpython-313-x86_64-linux-gnu.so -> src/liburing
copying build/lib.linux-x86_64-cpython-313/liburing/helper.cpython-313-x86_64-linux-gnu.so -> src/liburing
copying build/lib.linux-x86_64-cpython-313/liburing/io_uring.cpython-313-x86_64-linux-gnu.so -> src/liburing
copying build/lib.linux-x86_64-cpython-313/liburing/liburing.cpython-313-x86_64-linux-gnu.so -> src/liburing
copying build/lib.linux-x86_64-cpython-313/liburing/type.cpython-313-x86_64-linux-gnu.so -> src/liburing
copying build/lib.linux-x86_64-cpython-313/liburing/version.cpython-313-x86_64-linux-gnu.so -> src/liburing
```
Works fine for `3.8 - 3.12`

According to https://docs.python.org/3.13/c-api/unicode.html 
> "Note:
The [Py_UNICODE](https://docs.python.org/3.13/c-api/unicode.html#c.Py_UNICODE) representation has been removed since Python 3.12 with deprecated APIs. See [PEP 623](https://peps.python.org/pep-0623/) for more information."

### Code to reproduce the behaviour:

```cython
# example code
```

### Expected behaviour

_No response_

### OS

Linux

### Python version

3.13.0a3

### Cython version

3.0.8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
It's deprecated in 3.13, so the existence of a function is now generating C warnings. Therefore move it to its own section to be included on demand.

Remove a limited API implementation for it - it isn't in the limited API so just shouldn't be usable there.

Fixes #5982

### CODE REVIEW

File: Cython/Utility/TypeConversion.c [hunk 1]
```diff
@@ -1181,7 +1161,7 @@ static PyObject *__Pyx_c_func_ptr_to_capsule(__Pyx_generic_func_pointer funcptr,
     } else {
         // on all other platforms (which is the vast majority, since POSIX require a function pointer
         // can be  converted to a void*) we skip the allocation and store directly into the capsule's value.
-        // Use memcpy copy the data from the function pointer to the void* 
+        // Use memcpy copy the data from the function pointer to the void*
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:1164]:
```suggestion
        // Use memcpy to copy the data from the function pointer to the void*.
```

File: Cython/Compiler/PyrexTypes.py [hunk 2]
```diff
@@ -2683,6 +2683,13 @@ def __init__(self, base_type):
                 self.from_py_function = "__Pyx_PyUnicode_AsUnicode"
             self.exception_value = "NULL"
 
+    def create_to_py_utility_code(self, env):
+        if self.to_py_function == "__Pyx_PyUnicode_FromUnicode":
+            # Not included in the standard TypeConversions.c string conversions because Py_UNICODE
+            # is deprecated.
+            env.use_utility_code(UtilityCode.load_cached("pyunicode_from_unicode", "StringTools.c"))
+        return super().create_to_py_utility_code(env)
+
```
Comment (scoder) [inline Cython/Compiler/PyrexTypes.py:2692]: In order to avoid this special case (where, really, all of the conversion functions are special in their own way), I suggest adding a `to_py_utility_code` attribute in this class that can hold required utility code (`None` in the class's default), set at need by `__init__`, where we distinguish the cases already. `CTypeDefType` does something similar (but loads the code later when we know more about the context).

I also don't think we need to call `super()` if there's utility code available. Subclasses don't do that either.

File: Cython/Compiler/ExprNodes.py [hunk 3]
```diff
@@ -5499,6 +5499,8 @@ def generate_result_code(self, code):
                         base_result,
                         start_code,
                         code.error_goto_if_null(result, self.pos)))
+                code.globalstate.use_utility_code(
+                          UtilityCode.load_cached("pyunicode_from_unicode", "StringTools.c"))
```
Comment (scoder) [inline Cython/Compiler/ExprNodes.py:5503]:
```suggestion
                code.globalstate.use_utility_code(
                    UtilityCode.load_cached("pyunicode_from_unicode", "StringTools.c"))
```

File: Cython/Compiler/ExprNodes.py [hunk 4]
```diff
@@ -5508,6 +5510,8 @@ def generate_result_code(self, code):
                         stop_code,
                         start_code,
                         code.error_goto_if_null(result, self.pos)))
+                code.globalstate.use_utility_code(
+                          UtilityCode.load_cached("pyunicode_from_unicode", "StringTools.c"))
```
Comment (scoder) [inline Cython/Compiler/ExprNodes.py:5514]:
```suggestion
                code.globalstate.use_utility_code(
                    UtilityCode.load_cached("pyunicode_from_unicode", "StringTools.c"))
```

**Review by scoder — COMMENTED** [review]
Thanks. Yes, `Py_UNICODE` really needs to go out of the way.

**Comment by scoder** [comment]
Ah, yes, that is the best place to put it. That's beautiful. :)

**Comment by da-woods** [comment]
I've merged this into 3.1 for now. I suspect this should go back to 3.0.x, but it is just a warning so probably isn't absolutely essentially.

**Comment by scoder** [comment]
It's a warning that we produce, though, and that users cannot do anything about. Many users try to generate warning-free code and expect us to help with that - or at least not get in the way. We should do our best to make sure that the change doesn't hurt and backport it.
