### PR TITLE
Handle typedefs in ufuncs

### LINKED ISSUE #6161: [BUG] numpy types cannot be used for ufunc arguments
### Describe the bug

Using numpy's C types for ufunc declarations raises a very long error.

```
Compiling /home/mnoethe/test/cython/test_numpy_ufunc.pyx because it changed.
[1/1] Cythonizing /home/mnoethe/test/cython/test_numpy_ufunc.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from stdlib.stdint import int64_t

np.import_array()

@cython.ufunc
cdef np.int64_t add_one(np.int64_t x):
     ^
------------------------------------------------------------

test_numpy_ufunc.pyx:9:5: Type 'int64_t' cannot be used as a ufunc argument


...
```

### Code to reproduce the behaviour:

```cython
#cython: language_level=3
cimport cython
cimport numpy as np

np.import_array()

@cython.ufunc
cdef np.int64_t add_one(np.int64_t x):
    return x + 1

```

### Expected behaviour

Numpy ufuncs work with numpy data types.

### OS

Linux, Ubuntu 22.04

### Python version

3.11

### Cython version

cython                    3.0.10          py311hb755f60_0    conda-forge

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
~Extern typedefs~ Mapping of type to Numpy constant gets left to the C compiler to sort out since we can't rely on Cython having been told correctly.

Also fixes issues with using types written as `cimported_module.type` - these weren't visible in the utility code scope. Types are now declared in the utility code scope only using a temporary name instead.

Closes #6161

### CODE REVIEW

File: Cython/Utility/UFuncs_C.c [hunk 1]
```diff
@@ -14,6 +14,58 @@
...
+    (((tp)-1) < (tp)0) ? \
+        (__PYX_GET_NPY_SINT_TYPE(tp)) : \
+        (__PYX_GET_NPY_UINT_TYPE(tp))
+
+static int __Pyx_validate_ufunc_types(char *types, Py_ssize_t count, Py_ssize_t input_count);
+
+/////////////////////// UFuncTypeHandling ///////////////
+
+// DW - it's a bit of a shame that this has to be a runtime check since the C compiler does
+// know it. We could make this a compile-time error in C++, but not easily in C.
```
Comment (scoder) [inline Cython/Utility/UFuncs_C.c:51]: It could potentially figure it out if it inlines the validation function. But how many types do you expect here? One, two, three? Probably rarely more, right? Why not call the validation function multiple times, instead of using a loop? You could also inline the `NPY_NOTYPE` comparison and keep the helper function only for setting the exception. That should make it easy for the C compiler to discard the calls in the normal cases.

**Review by scoder — COMMENTED** [review]
Yes, seems good to move the exact typing to C compile time.

File: Cython/Utility/UFuncs_C.c (hunk 1 above)
Comment (da-woods) [reply Cython/Utility/UFuncs_C.c:51]: Ah I think you're slightly misunderstanding the comment.

What I really want is a failure from the C compiler because it already knows that it's used `NPY_NOTYPE`. I'm not worried about the cost of the validation function. I wish I didn't have to try to import the module to work out that I've got it wrong.

Comment (da-woods) [reply Cython/Utility/UFuncs_C.c:51]: Yeah possibly. I'll have another look and see if I can do something like that.

**Comment by cgohlke** [comment]
Does this PR support `char`, `long long`, and `unsigned *` C types that are currently failing with Cython 3.0.10?

For example:
```cython
@cython.ufunc
cdef char _test():
    return 0
```
fails with
```
Type 'char' cannot be used as a ufunc argument
```

Mapping `bint` to `NPY_BOOL` would also be nice.

**Comment by da-woods** [comment]
> Does this PR support `char`, `long long`, and `unsigned *` C types that are currently failing with Cython 3.0.10?

I don't think it does - looking at it the mapping of numeric types probably needs another go because there's a lot that it misses.

> Mapping `bint` to `NPY_BOOL` would also be nice.

I'm a bit unsure if that can be made to work. The main issue is that Cython stores `bint` as an `int` and numpy as a byte.

**Comment by cgohlke** [comment]
I wanted to suggest the following changes but then saw this PR:
```diff
diff --git a/Cython/Compiler/UFuncs.py b/Cython/Compiler/UFuncs.py
index b75256790..fdaa00e7f 100644
--- a/Cython/Compiler/UFuncs.py
+++ b/Cython/Compiler/UFuncs.py
@@ -50,6 +50,21 @@ def _get_type_constant(pos, type_):
         elif type_ == PyrexTypes.c_longdouble_complex_type:
             return "NPY_CLONGDOUBLE"
     elif type_.is_numeric:
+        if type_ == PyrexTypes.c_char_type:
+            return "NPY_BYTE"
+        if type_ == PyrexTypes.c_uchar_type:
+            return "NPY_UBYTE"
+        if type_ == PyrexTypes.c_ushort_type:
+            return "NPY_USHORT"
+        if type_ == PyrexTypes.c_uint_type:
+            return "NPY_UINT"
+        if type_ == PyrexTypes.c_ulong_type:
+            return "NPY_ULONG"
+        if type_ == PyrexTypes.c_longlong_type:
+            return "NPY_LONGLONG"
+        if type_ == PyrexTypes.c_ulonglong_type:
+            return "NPY_ULONGLONG"
+
         postfix = type_.empty_declaration_code().upper().replace(" ", "")
         typename = "NPY_%s" % postfix
         if typename in numpy_numeric_types:
```

**Comment by da-woods** [comment]
I think I might just go through the "typedef" type deduction even for real known types. It's all calculated at compile-time so has no real cost. It keeps the logic in one place. And it matches everything exactly with `sizeof` so it's guaranteed to be right.
