### PR TITLE
Additional unordered_map template defaults

### LINKED ISSUE #3685: Additional unordered_map template defaults
```unordered_map``` is currently defined with only its key and value parameters, not any of the additional parameters it supports (HASH, PRED, ALLOCATOR):

    cdef extern from "<unordered_map>" namespace "std" nogil:
        cdef cppclass unordered_map[T, U]:

```unordered_set``` however is defined with support for them:

    cdef extern from "<unordered_set>" namespace "std" nogil:
        cdef cppclass unordered_set[T,HASH=*,PRED=*,ALLOCATOR=*]:

I hit a concrete usecase of wanting to be able to pass HASH to support non-standard key types:

    unordered_map[vector[int], int] int_vector_map

which currently yields

    error: implicit instantiation of undefined template 'std::__1::hash<std::__1::vector<int, std::__1::allocator<int> > >'
    : public integral_constant<bool, __is_constructible(_Tp, _Args...)>

I have this added with a test in a [branch](https://github.com/wrmsr/cython/commit/22d7741cebca4342d8f503cf3ab660bd8e049009), PR to be posted after this.

### PR DESCRIPTION
**Pull request by wrmsr**
Closes #3685.

### CODE REVIEW

File: tests/run/cpp_unordered_map_helper.h [hunk 1]
```diff
@@ -0,0 +1,12 @@
+#include <vector>
+
+struct IntVectorHash {
+  size_t operator()(const std::vector<int>& v) const {
+    std::hash<int> hasher;
```
Comment (da-woods) [inline tests/run/cpp_unordered_map_helper.h:5]: Do you need to include something to ensure `std::hash` is available? I know it's probably included with `unordered_map` but I don't know that you can/should 100% rely on the order Cython includes stuff.

File: tests/run/cpp_stl_cpp11.pyx [hunk 2]
```diff
@@ -140,6 +140,11 @@ def test_unordered_set_functionality():
     return "pass"
 
 
+cdef extern from "cpp_unordered_map_helper.h":
```
Comment (scoder) [inline tests/run/cpp_stl_cpp11.pyx:143]: You can also just include the C++ code as a literal docstring here. That avoids having to look up another file when reading through the test.
