### PR TITLE
Fix a crash in sys.monitoring

### LINKED ISSUE #7050: [BUG] Monitoring support can result in use-after-free when tracing
### Summary

tl;dr I think there is currently a bug in how Cython's monitoring support handles tracing. [`__Pyx_TraceFrameInit` assigns to the current frame object](https://github.com/cython/cython/blob/595ba7c9ebf071ce486d411a8b2384e5291a2239/Cython/Utility/Profile.c#L122C7-L122C48), [`__Pyx_TraceStartFunc`](https://github.com/cython/cython/blob/595ba7c9ebf071ce486d411a8b2384e5291a2239/Cython/Utility/Profile.c#L150) takes care of [increfing the frame for the lifetime of the function where tracking is occurring](https://github.com/cython/cython/blob/595ba7c9ebf071ce486d411a8b2384e5291a2239/Cython/Utility/Profile.c#L167), and [`__Pyx_PyMonitoring_ExitScope`](https://github.com/cython/cython/blob/595ba7c9ebf071ce486d411a8b2384e5291a2239/Cython/Utility/Profile.c#L134) will [handle the decref](https://github.com/cython/cython/blob/595ba7c9ebf071ce486d411a8b2384e5291a2239/Cython/Utility/Profile.c#L145) (for simplicity I'm assuming that we take the `nogil` paths. The problem is that `__Pyx_TraceStartFunc` checks whether the current thread is in tracing mode, while `__Pyx_PyMonitoring_ExitScope` does not. That means that when tracing, the monitoring loop injected into Cython-generated functions will decref without increfing, resulting in prematurely freeing the frame object.

### Proposed solution

If my diagnosis is correct, I think the best solution is likely for `__Pyx_TraceStartFunc` to record whether or not it increfed the frame inside the `if(!__Pyx_PyThreadState_Current->tracing)` block, and then `__Pyx_PyMonitoring_ExitScope` could use that value to only decref conditionally. I don't know whether it is likely for one thread to change the tracing state of another thread, but especially given the potential use of free-threaded Python builds I would be inclined to play it safe and put a lock around the check. I don't know if that is really necessary though, I'll defer to the Cython developers on that.

### Long description

We recently started observing intermittent segmentation faults in CI for some RAPIDS libraries. Some of these are documented in [this cuml issue](https://github.com/rapidsai/cuml/issues/7012), and others can be seen in CI runs [like this one for cudf](https://github.com/rapidsai/cudf/actions/runs/16322634857/job/46106683933?pr=19369#step:10:2716). These seemingly implicated a recent release of [numba-cuda](https://github.com/NVIDIA/numba-cuda/), so we [rolled back the upgrade](https://github.com/rapidsai/cudf/pull/19413). Among the primary changes in numba-cuda was the usage of the [cuda_bindings](https://github.com/NVIDIA/cuda-python/tree/main/cuda_bindings) package in some new places. We produced a simpler reproducer (shown below). Here is a representative backtrace at the point of one of the segmentation faults, suggesting a problem inside the cuda-bindings Cython code:

```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fb750df427e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fb750dd78ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000561dc445d3cf in fatal_error_exit (status=-1) at /usr/local/src/conda/python-3.13.5/Python/pylifecycle.c:3256
#6  0x0000561dc445d94d in fatal_error (fd=2, header=1, prefix=0x561dc4563cf0 <__func__.1> "_PyObject_AssertFailed", msg=0x561dc4563b78 "_PyObject_AssertFailed", status=-1) at /usr/local/src/conda/python-3.13.5/Python/pylifecycle.c:3472
#7  0x0000561dc445d9cd in _Py_FatalErrorFunc (func=0x561dc4563cf0 <__func__.1> "_PyObject_AssertFailed", msg=0x561dc4563b78 "_PyObject_AssertFailed") at /usr/local/src/conda/python-3.13.5/Python/pylifecycle.c:3488
#8  0x0000561dc42c1339 in _PyObject_AssertFailed (obj=0x7fb74e481b70, expr=0x0, msg=0x561dc4563394 "object has negative ref count", file=0x7fb74ee44020 "/opt/conda/envs/test/include/python3.13d/object.h", line=1042,
    function=0x561dc4563c50 <__func__.5> "_Py_NegativeRefcount") at /usr/local/src/conda/python-3.13.5/Objects/object.c:2916
#9  0x0000561dc42bd61b in _Py_NegativeRefcount (filename=0x7fb74ee44020 "/opt/conda/envs/test/include/python3.13d/object.h", lineno=1042, op=0x7fb74e481b70) at /usr/local/src/conda/python-3.13.5/Objects/object.c:265
#10 0x00007fb74e5ea9da in Py_DECREF (filename=0x7fb74ee44020 "/opt/conda/envs/test/include/python3.13d/object.h", lineno=1042, op=0x7fb74e481b70) at /opt/conda/envs/test/include/python3.13d/object.h:926
#11 0x00007fb74e5eaa78 in Py_XDECREF (op=0x7fb74e481b70) at /opt/conda/envs/test/include/python3.13d/object.h:1042
#12 0x00007fb74e630784 in __pyx_pf_4cuda_8bindings_6driver_11CUdeviceptr_2__dealloc__ (__pyx_v_self=0x7faff8deec40) at cuda/bindings/driver.cpp:52267
#13 0x00007fb74e63054c in __pyx_pw_4cuda_8bindings_6driver_11CUdeviceptr_3__dealloc__ (__pyx_v_self=0x7faff8deec40) at cuda/bindings/driver.cpp:52241
#14 0x00007fb74ec441c5 in __pyx_tp_dealloc_4cuda_8bindings_6driver_CUdeviceptr (o=0x7faff8deec40) at cuda/bindings/driver.cpp:615395
```

cuda/bindings/driver.cpp is generated from [this Cython source file](https://github.com/NVIDIA/cuda-python/blob/main/cuda_bindings/cuda/bindings/driver.pyx.in). On initial investigation, the Cython-generated C++ code seems unproblematic. If we look at the last frame from the driver.cpp file in the backtrace above, though, we see this:

```
#12 0x00007fb74e630784 in __pyx_pf_4cuda_8bindings_6driver_11CUdeviceptr_2__dealloc__ (__pyx_v_self=0x7faff8deec40) at cuda/bindings/driver.cpp:52267
52267     __Pyx_PyMonitoring_ExitScope(0);
(gdb) l
52262     #else
52263     __Pyx_TraceReturnValue(NULL, 0, 0, __PYX_ERR(0, 4766, __pyx_L1_error));
52264     #endif
52265     __Pyx_WriteUnraisable("cuda.bindings.driver.CUdeviceptr.__dealloc__", __pyx_clineno, __pyx_lineno, __pyx_filename, 1, 0);
52266     __pyx_L0:;
52267     __Pyx_PyMonitoring_ExitScope(0);
52268   }
52269
52270   /* "cuda/bindings/driver.pyx":4768
52271    *     def __dealloc__(self):
```

That indicates to me that the `__Pyx_PyMonitoring_ExitScope` call is decrefing an object that should still be in scope at this point. The only object it decrefs is the local scope's frame, and with suitable breakpoints we can inspect with gdb to confirm that this object's ref count is indeed dropping to zero prematurely.

To further narrow down the issue, I printed the reference count of the frame after `__Pyx_TraceStartFunc` and `__Pyx_PyMonitoring_ExitScope`, and as expected I see it being incremented and decremented each time, until suddenly on one iteration there is no change to the value after `__Pyx_TraceStartFunc` and then the next call to `__Pyx_PyMonitoring_ExitScope` drops the reference count to zero. Inspecting the two macros, the only way I could see the incref not happening is if tracing was on, so I reran the same experiment and printed the value of tracing. As expected, I see that the failure to incref happens on the first iteration where tracing is enabled. 

### Code to reproduce the behaviour:

This is the reproducer that I used, but it also requires more work to get a suitable environment set up since it involves using specific versions of the libraries and environment. We've been running this with `python -m pytest --cov cuml -p cudf.pandas --cache-clear -vs -x repro.py -s` (also requires `pytest-cov` installed to ensure that coverage testing is activated). Hopefully my diagnosis above is sufficient to move things forward, otherwise I can try to help a Cython developer get things set up. I can also try and put together a simpler reproducer if needed.
```cython
from cuml.testing.test_preproc_utils import assert_allclose, create_rand_clf, convert
from cuml.internals.input_utils import determine_array_type_full
from cuml.internals.input_utils import input_to_cuml_array
from cuml.internals.api_context_managers import BaseReturnArrayCM
import numpy as np
import cupy as cp
from numba import cuda
from cuml.preprocessing import MinMaxScaler
from sklearn.preprocessing import minmax_scale as sk_minmax_scale
from cuml.preprocessing import minmax_scale as cu_minmax_scale
from cuml.thirdparty_adapters.adapters import check_array
from cuml.internals.global_settings import GlobalSettings


def test_segfault():
    # typically segfaults before 1,000 iterations, often <700
    dataset = cp.random.uniform(size=(500, 20))
    X = cuda.as_cuda_array(dataset)

    # Note: `copy=True` seems important. With `copy=False`, we ran
    # to 10,000 iterations without issue.
    scaler = MinMaxScaler(copy=True)
    scaler.fit(X)

    for i in range(10000):
        print(f"iteration {i}")


        scaler.transform(X)
```

### Expected behaviour

The reference count should be maintained correctly when tracing. I am aware that [the documentation for `CYTHON_USE_SYS_MONITORING` says that coverage will not work with it](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#c-macro-defines), but I presume that is intended to indicate that Cython coverage measurements will fail, not that Cython code will fail arbitrarily when run under coverage.

### OS

Linux

### Python version

3.13.15

### Cython version

3.1.2

### Additional context

I actually wouldn't expect any of this code to be executed since I don't have Cython profiling on. I have opened that issue separately in #7051. For now, setting `CYTHON_USE_SYS_MONITORING` to 0 should bypass this issue.

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #7050

Happens with a function with monitoring/tracing is used within a sys.monitoring handler.  In this case, the reference counting of `__code__` is inconsistent.

### CODE REVIEW

File: Cython/Utility/Profile.c [hunk 1]
```diff
@@ -157,18 +157,18 @@
               if (!__Pyx_PyThreadState_Current->tracing) {                                   \
                   if (likely($frame_code_cname)) Py_INCREF($frame_code_cname);               \
                   else $frame_code_cname = (PyObject*) __Pyx_createFrameCodeObject(funcname, srcfile, firstlineno); \
-                  if (unlikely(!$frame_code_cname)) goto_error;                              \
-                  ret = __Pyx__TraceStartFunc($monitoring_states_cname, $frame_code_cname, offset, skip_event); \
-              }                                                                              \
+                  if (unlikely(!$frame_code_cname)) ret = -1;                                \
+                  else ret = __Pyx__TraceStartFunc($monitoring_states_cname, $frame_code_cname, offset, skip_event); \
+              } else $frame_code_cname = NULL;                                               \
```
Comment (da-woods) [inline Cython/Utility/Profile.c:162]: My view is "we know we're not going to need the code object so just make it NULL and we wont have to reference count it.  The other option would be to always initialize/reference count it.

File: Cython/Utility/Profile.c [hunk 2]
```diff
@@ -157,18 +157,18 @@
               if (!__Pyx_PyThreadState_Current->tracing) {                                   \
                   if (likely($frame_code_cname)) Py_INCREF($frame_code_cname);               \
                   else $frame_code_cname = (PyObject*) __Pyx_createFrameCodeObject(funcname, srcfile, firstlineno); \
-                  if (unlikely(!$frame_code_cname)) goto_error;                              \
-                  ret = __Pyx__TraceStartFunc($monitoring_states_cname, $frame_code_cname, offset, skip_event); \
-              }                                                                              \
+                  if (unlikely(!$frame_code_cname)) ret = -1;                                \
```
Comment (da-woods) [inline Cython/Utility/Profile.c:160]: Unrelated to the bug, but we shouldn't be jumping out of a PyGILState_Ensure/Release block. I've changed the GIL side too just so it matches

**Review by scoder — APPROVED** [review]

**Comment by da-woods** [comment]
3.1.x commit is b434a3b5f
