### PR TITLE
Make classmethod work in limited-api

### LINKED ISSUE #5797: [BUG] classmethods don't compile using the limited api
### Describe the bug

Hello everyone,

When compiling a class with a classmethod using the limited API I get the following error:

```
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DCYTHON_LIMITED_API=1 -DPy_LIMITED_API=0x030B0000 -I/private/var/folders/l4/gpyzwv455hzbmbv78x05555h0000gn/T/build-env-ok8opy1u/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c limited_classmethod.cpp -o build/temp.macosx-14-arm64-cpython-311/limited_classmethod.o
limited_classmethod.cpp:6876:5: error: no matching function for call to 'Py_TYPE'
    __Pyx_PyHeapTypeObject_GC_Del(m);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
limited_classmethod.cpp:971:26: note: expanded from macro '__Pyx_PyHeapTypeObject_GC_Del'
    PyTypeObject *type = Py_TYPE(obj);\
                         ^~~~~~~
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/object.h:132:29: note: candidate function not viable: no known conversion from '__pyx_CyFunctionObject *' to 'PyObject *' (aka '_object *') for 1st argument
static inline PyTypeObject* Py_TYPE(PyObject *ob) {
                            ^
limited_classmethod.cpp:7396:9: error: use of undeclared identifier 'PyMethodDescrObject'; did you mean 'PyMethodDescr_Type'?
        PyMethodDescrObject *descr = (PyMethodDescrObject *)method;
        ^~~~~~~~~~~~~~~~~~~
        PyMethodDescr_Type
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/descrobject.h:22:26: note: 'PyMethodDescr_Type' declared here
PyAPI_DATA(PyTypeObject) PyMethodDescr_Type;
                         ^
limited_classmethod.cpp:7396:39: error: use of undeclared identifier 'PyMethodDescrObject'; did you mean 'PyMethodDescr_Type'?
        PyMethodDescrObject *descr = (PyMethodDescrObject *)method;
                                      ^~~~~~~~~~~~~~~~~~~
                                      PyMethodDescr_Type
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/descrobject.h:22:26: note: 'PyMethodDescr_Type' declared here
PyAPI_DATA(PyTypeObject) PyMethodDescr_Type;
                         ^
limited_classmethod.cpp:7396:60: error: expected expression
        PyMethodDescrObject *descr = (PyMethodDescrObject *)method;
                                                           ^
limited_classmethod.cpp:7396:30: error: use of undeclared identifier 'descr'
        PyMethodDescrObject *descr = (PyMethodDescrObject *)method;
                             ^
limited_classmethod.cpp:7400:32: error: use of undeclared identifier 'descr'
        PyTypeObject *d_type = descr->d_common.d_type;
                               ^
limited_classmethod.cpp:7402:47: error: use of undeclared identifier 'descr'
        return PyDescr_NewClassMethod(d_type, descr->d_method);
                                              ^
limited_classmethod.cpp:7405:14: error: use of undeclared identifier 'PyMethod_Check'
    else if (PyMethod_Check(method)) {
             ^
limited_classmethod.cpp:7406:34: error: use of undeclared identifier 'PyMethod_GET_FUNCTION'
        return PyClassMethod_New(PyMethod_GET_FUNCTION(method));
                                 ^
limited_classmethod.cpp:7409:16: error: use of undeclared identifier 'PyClassMethod_New'
        return PyClassMethod_New(method);
               ^
10 errors generated.

```

### Code to reproduce the behaviour:

```cython
# limited_classmethod.pyx

cdef class A:
    @classmethod
    def method(cls):
        pass
```

### Expected behaviour

It should compile.

### OS

_No response_

### Python version

_No response_

### Cython version

_No response_

### Additional context

classmethod implementation: https://github.com/cython/cython/blob/0f2a0d38b60e10e401aa1435801b2b8975083c7b/Cython/Utility/CythonFunction.c#L1754-L1804

### PR DESCRIPTION
**Pull request by da-woods**
Except for the case where binding=False, which I don't think we can easily do. I don't care that much given that binding=True works correctly.

Fixes #5797

### CODE REVIEW

File: Cython/Utility/CythonFunction.c [hunk 1]
```diff
@@ -1792,13 +1795,54 @@ static PyObject* __Pyx_Method_ClassMethod(PyObject *method) {
         PyTypeObject *d_type = descr->d_common.d_type;
         #endif
         return PyDescr_NewClassMethod(d_type, descr->d_method);
+#else
+        return PyErr_Format(
```
Comment (da-woods) [inline Cython/Utility/CythonFunction.c:1799]: I suspect it would be possible to cover this case by setting `METH_CLASS` when the `PyMethodDef` is defined. I definitely don't think that's worth it for the first pass and may not be worth it in general.

File: Cython/Utility/CythonFunction.c [hunk 2]
```diff
@@ -1792,13 +1795,54 @@ static PyObject* __Pyx_Method_ClassMethod(PyObject *method) {
...
+        PyObject *types_module, *method_type=NULL, *func=NULL;
+        PyObject *builtins, *classmethod, *result=NULL;
+        types_module = PyImport_ImportModule("types");
+        if (!types_module) {
+            return NULL;
+        }
+        method_type = PyObject_GetAttrString(types_module, "MethodType");
+        if (!method_type) goto bad;
+        if (__Pyx_TypeCheck(method, method_type)) {
+            func = PyObject_GetAttrString(method, "__func__");
```
Comment (vyasr) [inline Cython/Utility/CythonFunction.c:1827]: I'm sort of surprised that `PyMethod_GetFunction` isn't part of the limited API. I wonder if there's a plan to add it at some point. I had to write code like this in a couple of places and it made me wonder if getattr is really the intended way to access everything in limited API mode. I couldn't find any good alternatives, though.

File: Cython/Utility/CythonFunction.c [hunk 3]
```diff
@@ -1792,13 +1795,54 @@ static PyObject* __Pyx_Method_ClassMethod(PyObject *method) {
...
+            if (!func) goto bad;
+        } else {
+            func = method;
+            Py_INCREF(func);
+        }
+        builtins = PyEval_GetBuiltins(); // borrowed
+        if (!builtins) goto bad;
```
Comment (vyasr) [inline Cython/Utility/CythonFunction.c:1834]: Would it make sense to extract this logic into a macro? Every limited API branch is going to be repeating this pattern everywhere. I'm imagining something like
```
#define goto_if_null(var, expr, label) var=expr; if(!var) goto label;
...
goto_if_null(builtins, PyEval_GetBuiltins(), bad);
```

Having seen it written out I'm not as convinced of the benefit as I was in my head, but I'll leave the suggestion in case you find it helpful.

**Review by vyasr — APPROVED** [review]
The implementation looks fine. I'm not sure if there are improvements that could be made but I do think it is correct.

**Comment by da-woods** [comment]
I'm going to treat this as low impact, unlikely to break anything, and merge it in the fairly near future unless I get any objections...
