### PR TITLE
Fix overflow_check

### LINKED ISSUE #3588: overflow_check_* failures in tests
Running the tests with CC=-ftrapv shows that #1911 isn't the only overflow-related error and we're thus hitting undefined behaviour in other cases; notably in Overflow.c we often do operations on signed integers regardless of whether or not we're in the overflow case. PR forthcoming.

```
cython$ CFLAGS=-ftrapv python runtests.py overflow
Python 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0]

Running tests against Cython 3.0a4 3bba77a2bf9ed7da4c118fd7887658c597e14cd2
Using Cython language level 2.
Backends: c,cpp

Fatal Python error: Aborted

Thread 0x00007fb5bcdce700 (most recent call first):
  File "runtests.py", line 2267 in time_stamper
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fb5bdda3740 (most recent call first):
  File "<doctest overflow_check_int.test_add_const[1]>", line 1 in <module>
  File "/usr/lib/python3.8/doctest.py", line 1329 in __run
  File "/usr/lib/python3.8/doctest.py", line 1476 in run
  File "/usr/lib/python3.8/doctest.py", line 2191 in runTest
  File "/usr/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
  File "/usr/lib/python3.8/unittest/case.py", line 676 in run
  File "/usr/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/usr/lib/python3.8/unittest/suite.py", line 122 in run
  File "runtests.py", line 1315 in run_test
  File "runtests.py", line 1321 in run_forked_test
  File "runtests.py", line 1316 in run_doctests
  File "runtests.py", line 1304 in run_tests
  File "runtests.py", line 1286 in run
  File "/usr/lib/python3.8/unittest/case.py", line 736 in __call__
  File "/usr/lib/python3.8/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.8/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.8/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.8/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.8/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.8/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.8/unittest/runner.py", line 176 in run
  File "runtests.py", line 2573 in runtests
  File "runtests.py", line 2209 in main
  File "runtests.py", line 2595 in <module>
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #3588, and while we're at it improves all the (arithmetic) overflow detection code, including adding support for the gcc 5+/clang 3.4+ `__builtin_XXX_overflow`.

Looking at `Demos/benchmarks/chaos.py` (the only file in that directory significantly affected by enabling `overflowcheck`, with the non-`__builtin_XXX_overflow` code paths we gain 2%, and with them we gain 4% (and that's then only 1% behind `overflowcheck=False`).

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

File: Cython/Utility/Overflow.c [hunk 1]
```diff
@@ -46,6 +46,22 @@ static int __Pyx_check_twos_complement(void) {
 #define __Pyx_div_no_overflow(a, b, overflow) ((a) / (b))
 #define __Pyx_div_const_no_overflow(a, b, overflow) ((a) / (b))
 
+#if defined(__has_builtin)
+#  if __has_builtin(__builtin_add_overflow) && !defined(__ibmxl__)
+#    define HAVE_BUILTIN_OVERFLOW
```
Comment (da-woods) [inline Cython/Utility/Overflow.c:51]: I think most macros like this start with `CYTHON_` (e.g. `CYTHON_HAVE_BUILTIN_OVERFLOW`), just to reduce the chances of conflicting with someone else's macro.

File: Cython/Utility/Overflow.c [hunk 2]
```diff
@@ -46,6 +46,14 @@ static int __Pyx_check_twos_complement(void) {
 #define __Pyx_div_no_overflow(a, b, overflow) ((a) / (b))
 #define __Pyx_div_const_no_overflow(a, b, overflow) ((a) / (b))
 
+#if defined(__GNUC__)
+#  define __Pyx_constant_p(x) (__builtin_constant_p(x))
```
Comment (scoder) [inline Cython/Utility/Overflow.c:58]: `__Pyx_is_constant(x)` ?

File: Cython/Utility/Overflow.c [hunk 3]
```diff
@@ -95,20 +108,28 @@ static CYTHON_INLINE {{UINT}} __Pyx_mul_{{NAME}}_checking_overflow({{UINT}} a, {
         return r;
 #endif
     } else {
-        {{UINT}} prod = a * b;
-        double dprod = ((double) a) * ((double) b);
+        // somewhat surprisingly, at least on x86_64 it's quicker to use floats (c.f. the const
+        // variant below)
```
Comment (scoder) [inline Cython/Utility/Overflow.c:146]: Ok, but – is the value range large enough to cover an `unsigned long long` multiplication?

File: Cython/Utility/Overflow.c [hunk 4]
```diff
@@ -95,20 +108,28 @@ static CYTHON_INLINE {{UINT}} __Pyx_mul_{{NAME}}_checking_overflow({{UINT}} a, {
...
+        *overflow |= fabs(fprod - r) > ((float)(__PYX_MAX({{UINT}})) / 2);
+        return r;
     }
 }
 
 static CYTHON_INLINE {{UINT}} __Pyx_mul_const_{{NAME}}_checking_overflow({{UINT}} a, {{UINT}} b, int *overflow) {
-    if (b > 1) {
-        *overflow |= a > __PYX_MAX({{UINT}}) / b;
+    if (__Pyx_constant_p(a) && !__Pyx_constant_p(b)) {
+        // paranoia
```
Comment (scoder) [inline Cython/Utility/Overflow.c:158]: I'm aware that there's a longer comment in the signed variant further down, but it seems worth repeating it here. For a future reader, it will be less obvious what the 'paranoia' refers to. (I'm ok with keeping this safety check in general.)

File: Cython/Utility/Overflow.c [hunk 5]
```diff
@@ -170,17 +170,17 @@ static CYTHON_INLINE {{INT}} __Pyx_add_const_{{NAME}}_checking_overflow({{INT}}
     } else if (b < 0) {
         *overflow |= a < __PYX_MIN({{INT}}) - b;
     }
-    return a + b;
+    return ({{INT}}) ((unsigned {{INT}}) a + (unsigned {{INT}}) b);
```
Comment (scoder) [inline Cython/Utility/Overflow.c]: Could you at least add a comment here? It's not obvious from seeing the code that this is doing something reasonable.

I think referring to the SO question might be ok:
https://stackoverflow.com/questions/4240748/allowing-signed-integer-overflows-in-c-c

**Review by scoder — COMMENTED** [review]
Nice! I left some comments, mostly about readability. This code is so deeply technical that it's worth dropping a comment more here and there.

File: Cython/Utility/Overflow.c (hunk 3 above)
Comment (gsnedders) [reply Cython/Utility/Overflow.c:146]: Looking at this much more closely, this is actually unsafe when `unsigned long long` is 64-bit (the original intent of this file was to allow false-positive overflow reporting, but not false-negatives, but I realise elsewhere we always raise OverflowError if this is truthy) unless we tightly control rounding modes due to 2^64 - 1 not being a possible value (and we probably don't want to get into changing rounding mode because that's a world of pain!), which is likewise true with a double.

I'm also doubting myself as to whether this is actually quicker v. the const version for the unsigned case anyway…

**Review by gsnedders — COMMENTED** [review]
I did write some comments, but wasn't sure quite how far to go given I'd spent long enough staring at the code, so did partly put this up as it was just to see where you wanted more! Looking at this code again (I wrote most of it a while ago) I can't say I disagree.

**Comment by gsnedders** [comment]
@scoder ping

**Comment by scoder** [comment]
Thanks!
I'll target this to 3.0 for now, mostly to give it some more testing. Wouldn't mind backporting it to 0.29.x at some point.
