### PR TITLE
Explicitly set exception cause in __Pyx_Generator_Replace_StopIteration

### LINKED ISSUE #5953: [BUG] Cython `@contextlib.contextmanager` unexpectedly turns StopIteration into a RuntimeError
### Describe the bug

Given a pure Python context manager like:
```py
@contextlib.contextmanager
def nullcontext():
    yield
```
a `StopIteration` raised inside of the `with` block will propagate out.

If you implement that exact context manager in Cython instead, the `StopIteration` exception will be replaced with a `RuntimeError`.

### Code to reproduce the behaviour:

```shell-session
git clone https://gist.github.com/godlygeek/3b461adb37d99f77ba470d79745a5c2c /tmp/reproducer
cd /tmp/reproducer
python3 -m venv venv
. venv/bin/activate
pip install .
python test.py
```

### Expected behaviour

That reproducer installs a Python package with 2 modules. One is a pure Python module, the other is a Cython-compiled version of that same pure Python source. The `test.py` imports a context manager from each of them, and uses both in the same way. We should get the same output from both, but instead we see:
```text
--------------------------------------------------
testing py_nullcontext
caught StopIteration
--------------------------------------------------
testing cy_nullcontext
Traceback (most recent call last):
  File "/tmp/reproducer/test.py", line 11, in <module>
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/reproducer/test.py", line 10, in <module>
    with func():
  File "/opt/bb/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "pymodule.py", line 5, in nullcontext
    yield
RuntimeError: generator raised StopIteration
```

### OS

Linux

### Python version

3.12.0

### Cython version

3.0.8

### Additional context

This is likely due to https://peps.python.org/pep-0479/ but something must be incorrect with the logic about when to apply it, seeing as how this results in a behavior difference from CPython.

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #5953

### CODE REVIEW

File: Cython/Utility/Coroutine.c [hunk 1]
```diff
@@ -301,8 +301,11 @@ static void __Pyx_Generator_Replace_StopIteration(int in_async_gen); /*proto*/
 //@requires: Exceptions.c::GetException
 
 static void __Pyx_Generator_Replace_StopIteration(int in_async_gen) {
-    PyObject *exc, *val, *tb, *cur_exc;
+    PyObject *val, *cur_exc, *new_exc;
+    #if __PYX_LIMITED_VERSION_HEX < 0x030C0000
```
Comment (da-woods) [inline Cython/Utility/Coroutine.c:305]: I think this just needs the 3.12 special-casing removed (because it isn't really the same) and then it should work...

File: Cython/Utility/Coroutine.c [hunk 2]
```diff
@@ -318,19 +318,19 @@ static void __Pyx_Generator_Replace_StopIteration(int in_async_gen) {
...
-    Py_XDECREF(val);
     Py_XDECREF(tb);
-    PyErr_SetString(PyExc_RuntimeError,
+    new_exc = PyObject_CallFunction(PyExc_RuntimeError, "s",
         #ifdef __Pyx_StopAsyncIteration_USED
         is_async_stopiteration ? "async generator raised StopAsyncIteration" :
         in_async_gen ? "async generator raised StopIteration" :
         #endif
         "generator raised StopIteration");
+    PyException_SetCause(new_exc, val); // steals ref to val
```
Comment (da-woods) [inline Cython/Utility/Coroutine.c:332]:
```suggestion
    if (!new_exc) {
        Py_XDECREF(val);
        return;
    }
    PyException_SetCause(new_exc, val); // steals ref to val
```
