### PR TITLE
Modified "pretend_to_initialize" for c++

### LINKED ISSUE #5278: [BUG] UB from __Pyx_pretend_to_initialize not initializing
### Describe the bug

Apologies in advance: I don't use cython, but I'm debugging a bug caused by using cython with a fresh version of clang. I'll try to get a better repro soon, but for now I'm just filing this in case the cause/fix is obvious. My repro is representative of something internal, but I haven't reduced it to something standalone yet.

With a very new [LLVM commit](https://github.com/llvm/llvm-project/commit/b6a0be8ce3114d0c57e7a7d6c3c222986ca506ad), we're seeing failures in Cython code. The issue seems to be caused by UB in Cython when returning uninitialized data.

Given some Cython code like this:

```cython
T decode(string encoded) except *:
  cdef T result
    if this.decoder.decode(encoded, &result):
      return result
  raise ValueError(f'Failed to decode {repr(encoded)}')

decode(.... <something invalid> ...)
```

The generated code for will look something like this:
```c++
static CYTHON_INLINE void __Pyx_pretend_to_initialize(void* ptr) { (void)ptr; }

template <typename T>
T decode(std::string __pyx_v_encoded) {
  T __pyx_v_result;
  T __pyx_r;
  ...
  __pyx_t_1 = (this->decoder.decode(__pyx_v_encoded, &__pyx_v_result) != 0);
  if (__pyx_t_1) {
    __pyx_r = __pyx_v_result;
    goto __pyx_L0;
  }
  ...
__pyx_L1_error:;
  __Pyx_pretend_to_initialize(&__pyx_r);
__pyx_L0:;
  return __pyx_r;  // This is only *actually* initialized in the happy case.
}
```

The UB is that `__Pyx_pretend_to_initialize` doesn't actually do any initialization, and so `decode` will return the uninitialized `__pyx_r` value. It's enough to silence static compiler warnings, but the optimizer will see that it doesn't do anything to the variable, and mis-optimize the UB accordingly.

There are two possible changes to `__Pyx_pretend_to_initialize` that would make it satisfy this requirement:

```c++
// Prevent the compiler from optimizing this away, e.g. see
// https://stackoverflow.com/questions/28287064/how-not-to-optimize-away-mechanics-of-a-folly-function
static CYTHON_INLINE void __Pyx_pretend_to_initialize(void* ptr) { asm volatile("" : "+r"(ptr)); }

// Or, make it actually do something. The compiler is hopefully smart enough to optimize this away, but I haven't checked.
// Requires changing the calls from __Pyx_pretend_to_initialize(&x) to __Pyx_pretend_to_initialize(&x, sizeof(x))
static CYTHON_INLINE void __Pyx_pretend_to_initialize(void* ptr, size_t size) { memset(ptr, 0, size); }
```

### Code to reproduce the behaviour:

```cython
T decode(string encoded) except *:
  cdef T result
    if this.decoder.decode(encoded, &result):
      return result
  raise ValueError(f'Failed to decode {repr(encoded)}')

decode(.... <something invalid> ...)
```

### Expected behaviour

When passed invalid data, it should raise an error. Instead, it crashes.

### Environment

OS: Linux
Python version: 3.10
Cython version: 0.29.32 (but I still see the bug in trunk)
LLVM/Clang version: something very recent; newer than this: https://github.com/llvm/llvm-project/commit/b6a0be8ce3114d0c57e7a7d6c3c222986ca506ad

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by da-woods**
In this case we actually have to initialize rather than just do nothing. Fixes #5278.

Supercedes #5296 (I think this is better since it limits the amount of work Cython itself has to do)

### CODE REVIEW

**Comment by scoder** [comment]
This seems better suited for a utility code file section than sequential code generation.

File: Cython/Utility/ModuleSetupCode.c [hunk 1]
```diff
@@ -2134,6 +2134,30 @@ static void __Pyx_FastGilFuncInit(void) {
 
 #endif
 
+///////////////////// PretendToInitialize ////////////////////////
+
+#if __cplusplus
```
Comment (da-woods) [inline Cython/Utility/ModuleSetupCode.c:2139]:
```suggestion
#ifdef __cplusplus
```
