### PR TITLE
Fixed CyFunction __self__ attribute

### LINKED ISSUE #4036: [BUG] `__self__`  attribute differs on Cython compiled functions
```
from wrapt import decorator

@decorator
def d1(wrapped, instance, args, kwargs):
    print(f'd1: {args}, {kwargs}')
    return wrapped(*args, **kwargs)

def d2(*argsT, **kwargsT):
    @decorator
    def d3(wrapped, instance, args, kwargs):
        print(f'd3: {argsT}, {kwargsT}, {args}, {kwargs}')
        return wrapped(*args, **kwargs)
    return d3

@d1
@d2(a=int, b=str)
def hello():
    print('hello')
```
Save above code as hello.py, use another module, import hello and call hello.hello(), all success.

```
import Cython.Build
import distutils.core
 
def py2c(file):
    cpy = Cython.Build.cythonize(file)
    distutils.core.setup(
	    name = 'test',
	    version = "1.0",
	    ext_modules= cpy,
	    author = "test",
	    author_email='test@163.com'
	)

if __name__ == '__main__':
    file = "hello.py"
    py2c(file)
```
Save above code as py2c.py, run "python py2c.py build_ext --inplace" ,it generate hello.pyd, import again, raise TypeError.

Expect it run success and print "hello".

 - OS: Windows 7
 - Python version 3.6.8
 - Cython version 0.29.22

raw_code
py2c
exception

### PR DESCRIPTION
**Pull request by da-woods**
The `__self__` argument should be present only for bound functions.
Fixes #4036

Currently it isn't easily possible to get this working absolutely
correctly for fused functions. I raise an attribute error but
`hasattr` still returns True

Additionally, Python 2 methods always have a `__self__` attribute
but set it to None. I follow Python 3 behaviour and don't have
the attribute

### CODE REVIEW

**Comment by da-woods** [comment]
It looks like I've possibly broken something to do with the __doc__ attribute on fused functions (and thus one of the test cases). It's a little surprising that not finding the Numpy tests was the only place this showed up though

File: Cython/Utility/CythonFunction.c [hunk 1]
```diff
@@ -1358,6 +1345,20 @@ __pyx_FusedFunction_call(PyObject *func, PyObject *args, PyObject *kw)
     return result;
 }
 
+static PyObject *
+__Pyx_FusedFunction_get_self(__pyx_FusedFunctionObject *m, CYTHON_UNUSED void *closure)
+{
+    PyObject *self;
+
+    self = m->self;
+    if (self == NULL) {
```
Comment (scoder) [inline Cython/Utility/CythonFunction.c:1354]: Let's consider the exception case "unlikely", simply because it's so costly any way.
```suggestion
    PyObject *self = m->self;
    if (unlikely(!self)) {
```

**Comment by scoder** [comment]
Thanks @da-woods !
