### PR TITLE
Simplify and optimize calls, using vectorcall on Python 3.8

### LINKED ISSUE #2996: _PyMethodDef_RawFastCallKeywords is used unsafely
The optimization #2850 is unsafe since it skips the type check of the `method_descriptor` object.

Minimal crashing example:
```
cdef class X:
    cdef long v
    def __cinit__(self):
        self.v = 1
    itervalues = type(object.__dict__).values

def test():
    return [v for v in X().itervalues()]
```

Suggestion: instead of using `_PyMethodDef_RawFastCallKeywords`, use the more generic `_PyObject_FastCall` or `_PyObject_Vectorcall`. I'll make a PR for this.

### PR DESCRIPTION
**Pull request by jdemeyer**
- Replace the `_PyMethodDef_RawFastCallKeywords` calls by `_PyMethodDescr_FastCallKeywords` to fix #2996 and add a test for it.
- Replace the manually-written code to call functions with a known number of arguments by calls to a new function `__Pyx_PyObject_FastCall`. The compiler should be able to optimize this if the number of arguments is a compile-time constant. Some special code for 0 and 1 arguments is still kept.
- In `__Pyx_PyObject_FastCall`, use code optimized for each CPython version. This includes vectorcall on Python 3.8 (enabled by a new feature test macro `CYTHON_VECTORCALL`)
- Remove `__Pyx_PyCFunction_FastCall` and `__Pyx_PyFastCFunction_Check` which seems no longer needed.
- In `__Pyx_PyObject_CallMatrixMethod`, call `__Pyx_PyObject_Call2Args` instead of essentially putting an inline copy of that function.

### CODE REVIEW

File: Cython/Utility/ObjectHandling.c [hunk 1]
```diff
@@ -2192,83 +2190,19 @@ static PyObject *__Pyx_PyFunction_FastCallDict(PyObject *func, PyObject **args,
...
-    PyTuple_SET_ITEM(args, 1, arg2);
-
-    Py_INCREF(function);
-    result = __Pyx_PyObject_Call(function, args, NULL);
-    Py_DECREF(args);
-    Py_DECREF(function);
-done:
-    return result;
+    PyObject *args[2] = {arg1, arg2};
+    return _PyObject_FastCall(function, args, 2);
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c]: This is lacking a guard for older CPythons (or you might have meant ` __Pyx_…`).

File: Cython/Utility/ObjectHandling.c [hunk 2]
```diff
@@ -2082,8 +2081,7 @@ static PyObject* __Pyx_PyFunction_FastCallNoKw(PyCodeObject *co, PyObject **args
 }
 
 
-#if 1 || PY_VERSION_HEX < 0x030600B1
-static PyObject *__Pyx_PyFunction_FastCallDict(PyObject *func, PyObject **args, int nargs, PyObject *kwargs) {
+static CYTHON_UNUSED PyObject *__Pyx_PyFunction_FastCallDict(PyObject *func, PyObject **args, int nargs, PyObject *kwargs) {
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c]: Can we somehow avoid the `CYTHON_UNUSED` here (if it's not too much hassle)? Better not generate code, than telling _some_ C compilers to silently ignore it.

File: Cython/Utility/ObjectHandling.c (hunk 1 above)
Comment (jdemeyer) [reply Cython/Utility/ObjectHandling.c]: Yes, I meant `__Pyx_`...

Comment (jdemeyer) [reply Cython/Utility/ObjectHandling.c]: And this `__Pyx_PyObject_FastCall` is better than upstream's `_PyObject_FastCall` since the latter doesn't optimize for the type `method_descriptor`.

**Comment by jdemeyer** [comment]
I noticed that `__Pyx_PyFunction_FastCallDict` is only ever called with `kwargs = NULL` so we could simplify that function. But I'll leave that for another PR.

File: Cython/Utility/ObjectHandling.c [hunk 3]
```diff
@@ -1853,44 +1911,15 @@ static PyObject* __Pyx_PyObject_CallMethod1(PyObject* obj, PyObject* method_name
...
-    Py_DECREF(args);
-    return result;
-}
-
 static PyObject* __Pyx_PyObject_CallMethod2(PyObject* obj, PyObject* method_name, PyObject* arg1, PyObject* arg2) {
     PyObject *args, *method = NULL, *result = NULL;
     int is_method = __Pyx_PyObject_GetMethod(obj, method_name, &method);
     if (likely(is_method)) {
-        result = __Pyx_PyObject_Call3Args(method, obj, arg1, arg2);
+        PyObject *args[3] = {arg1, arg2, arg3};
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c]: This should read `{obj, arg1, arg2}`.
Is this code not used anymore?

File: Cython/Utility/ObjectHandling.c [hunk 4]
```diff
@@ -2311,29 +2239,22 @@ static CYTHON_INLINE PyObject* __Pyx_PyObject_CallNoArg(PyObject *func); /*proto
...
+    if (PyCFunction_Check(func))
 #endif
     {
         if (likely(PyCFunction_GET_FLAGS(func) & METH_NOARGS)) {
             // fast and simple case that we are optimising for
             return __Pyx_PyObject_CallMethO(func, NULL);
         }
     }
-    return __Pyx_PyObject_Call(func, $empty_tuple, NULL);
+    return __Pyx_PyObject_FastCall(func, NULL, 0);
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c]: I don't think `NULL` is allowed in the non-vectorcall case.

Comment (jdemeyer) [reply Cython/Utility/ObjectHandling.c]: I'm pretty sure that it is allowed. For example CPython 3.6 has:
```
#define _PyObject_CallNoArg(func) \
    _PyObject_FastCall((func), NULL, 0)
```

File: Cython/Utility/ObjectHandling.c (hunk 3 above)
Comment (jdemeyer) [reply Cython/Utility/ObjectHandling.c]: > Is this code not used anymore?

It's not used anywhere. I removed it now.

**Comment by jdemeyer** [comment]
There was a problem with the cleanup code in `Cython/Compiler/ExprNodes.py`, causing a double `DECREF()` of the same temporary variable.

**Comment by jdemeyer** [comment]
Tests pass now!

**Comment by moreati** [comment]
>     * In `__Pyx_PyObject_FastCall`, use code optimized for each CPython version.

Naively, this sounds like it (partially) address #2263. Mentioning here, in case this PR can close an old ticket.

**Comment by scoder** [comment]
@moreati, this doesn't really do much about #2263. It changes the calling side, but not the callee side.

File: Cython/Utility/ObjectHandling.c [hunk 5]
```diff
@@ -2280,50 +2192,17 @@ static CYTHON_INLINE PyObject* __Pyx_PyObject_CallOneArg(PyObject *func, PyObjec
...
-#if CYTHON_FAST_PYCALL
-    if (PyFunction_Check(func)) {
-        return __Pyx_PyFunction_FastCall(func, &arg, 1);
-    }
-#endif
-    if (likely(PyCFunction_Check(func))) {
+    if (PyCFunction_Check(func)) {
         if (likely(PyCFunction_GET_FLAGS(func) & METH_O)) {
             // fast and simple case that we are optimising for
             return __Pyx_PyObject_CallMethO(func, arg);
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c]: I'm seeing a regression in the PyPy support (shows up in travis pypy3) due to this:
`ImportError: /home/travis/build/cython/cython/TEST_TMP/2/run/c/test_fstring/test_fstring.pypy3-58-x86_64-linux-gnu.so: undefined symbol: __Pyx_PyObject_CallMethO`
This code used to be guarded for CPython-only. It's probaby ok to just map this whole function to `…CallObjectArgs()` in non-CPython.

**Comment by jdemeyer** [comment]
I added some further simplifications: all the code for dealing with a specific number of arguments is now inside `__Pyx_PyObject_FastCall()`. If the compiler inlines everything as expected, the generated machine code should be essentially the same as before.

**Comment by scoder** [comment]
Thank you Jeroen!
