### PR TITLE
Fix CYTHON_LIMITED_API -> __PYX_LIMITED_VERSION_HEX 

### LINKED ISSUE #6361: Bad use of CYTHON_LIMITED_API
### Describe your issue

@da-woods `git blame` pointed to code you pushed in 2023. I think the way to use CYTHON_LIMITED_API may have changed. Are the following preprocessor guards still correct?

```console
$ git grep CYTHON_LIMITED_API Cython/Utility/Builtins.c
Cython/Utility/Builtins.c:#if !CYTHON_COMPILING_IN_LIMITED_API || CYTHON_LIMITED_API >= 0x030b0000
Cython/Utility/Builtins.c:#if !CYTHON_COMPILING_IN_LIMITED_API || CYTHON_LIMITED_API >= 0x030b0000
```

I was about to submit a PR with a change to use __PYX_LIMITED_VERSION_HEX, but the fact that its value is not set by default confused me. 

Or perhaps what we are needing is simply something like the following
```patch
diff --git a/Cython/Utility/ModuleSetupCode.c b/Cython/Utility/ModuleSetupCode.c
index 4482e75bd..5d9e3f4f8 100644
--- a/Cython/Utility/ModuleSetupCode.c
+++ b/Cython/Utility/ModuleSetupCode.c
@@ -194,6 +194,9 @@
   #ifdef Py_LIMITED_API
     #undef __PYX_LIMITED_VERSION_HEX
     #define __PYX_LIMITED_VERSION_HEX Py_LIMITED_API
+  #else
+    #undef __PYX_LIMITED_VERSION_HEX
+    #define __PYX_LIMITED_VERSION_HEX CYTHON_LIMITED_API
   #endif
   #define CYTHON_COMPILING_IN_PYPY 0
   #define CYTHON_COMPILING_IN_CPYTHON 0
```
and then always use the value of __PYX_LIMITED_VERSION_HEX wherever needed?

### PR DESCRIPTION
**Pull request by dalcinl**
Fixes #6361

### CODE REVIEW

File: Cython/Utility/ModuleSetupCode.c [hunk 1]
```diff
@@ -194,6 +194,9 @@
   #ifdef Py_LIMITED_API
     #undef __PYX_LIMITED_VERSION_HEX
     #define __PYX_LIMITED_VERSION_HEX Py_LIMITED_API
+  #elif CYTHON_LIMITED_API >= 0x03000000
```
Comment (dalcinl) [inline Cython/Utility/ModuleSetupCode.c:197]: @scoder This is IMO the only controversial part of this PR. What do you think?

Comment (da-woods) [reply Cython/Utility/ModuleSetupCode.c:197]: If we're doing this I think I'd change it to:

```
#if CYTHON_LIMITED_API != 1
    #undef __PYX_LIMITED_VERSION_HEX
    #define __PYX_LIMITED_VERSION_HEX CYTHON_LIMITED_API
#elif defined(Py_LIMITED_API)
    #undef __PYX_LIMITED_VERSION_HEX
    #define __PYX_LIMITED_VERSION_HEX Py_LIMITED_API
#endif
```

That makes user-preference override `Py_LIMITED_API` in general. And treats `1` as the only special value.

But wait to see what @scoder thinks...

Comment (dalcinl) [reply Cython/Utility/ModuleSetupCode.c:197]: In principle, I agree with you. However, what if both `CYTHON_LIMITED_API` and `Py_LIMITED_API` are defined to different values? The case `CYTHON_LIMITED_API <= Py_LIMITED_API` is probably OK, but I may be missing something. Should will add a check for that and `#error` if things are off?

Comment (da-woods) [reply Cython/Utility/ModuleSetupCode.c:197]: My thought is that `CYTHON_LIMITED_API <= Py_LIMITED_API` should work and might be useful to some people (maybe just for testing?). `CYTHON_LIMITED_API > Py_LIMITED_API` probably won't work but if users' want to request it then that's their choice.

I really don't know how useful this configurability is likely to be though.

Comment (scoder) [reply Cython/Utility/ModuleSetupCode.c:197]: Under normal circumstances, it should be enough to define `Py_LIMITED_API=0xV3R510N`, so that should be easy and "just work". While I also consider `CYTHON_LIMITED_API` more specific, I don't see why we should allow users to let it contradict the general CPython macro. It just leads to unrealistic build scenarios, even if we consider them test setups.

I'm fine with keeping `CYTHON_LIMITED_API` as a flag and requiring `Py_LIMITED_API` to set a specific target version.

**Comment by dalcinl** [comment]
@scoder @da-woods PR updated addressing your concerns. 
Now I'm only fixing `CYTHON_LIMITED_API` -> `__PYX_LIMITED_VERSION_HEX`.
Ready for merge?

**Comment by scoder** [comment]
Thanks
