### PR TITLE
 Fix the name of attributes in the common module 

### LINKED ISSUE #4373: [BUG] Shared implementation of CyFunction and FusedFunction has the wrong name
**Describe the bug + To Reproduce**

```
# has_function.pyx
def f(x):
    return x+1
```

Cythonize it with `cythonize -if has_function.pyx`, then:

```
>>> import has_function
>>> type(has_function.f)
<class '_cython_3_0_0a9.cython_function_or_method'>
>>> dir(_cython_3_0_0a9)
['__doc__', '__loader__', '__name__', '__package__', '__spec__', '_cython_3_0_0a9.cython_function_or_method']
>>> _cython_3_0_0a9._cython_3_0_0a9.cython_function_or_method(  
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module '_cython_3_0_0a9' has no attribute '_cython_3_0_0a9'
```

this appears to be general, but it's specifically causing issues with pickling functions in the limited API or with type-slots. I'm not completely sure why it makes a difference to those.

**Expected behavior**

The function name in the module should be `cython_function_or_method` (i.e. it shouldn't have the dotted qualname prefix)

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.8.10
 - Cython version: current master branch (3.0.9a ish)

**Additional context**

It's OK on 0.29.x (you need to change the example to set binding to True)
```
>>> dir(_cython_0_29_23)
['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'cython_function_or_method']
```

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #4373

~I also removed a bit of unused capsule-related implementation~

### CODE REVIEW

File: Cython/Utility/Coroutine.c [hunk 1]
```diff
@@ -1501,13 +1501,29 @@ static PyObject *__Pyx_CoroutineAwait_no_new(PyTypeObject *type, PyObject *args,
 }
 #endif
 
+#if PY_VERSION_HEX < 0x03060000
+// In earlier versions of Python an object with no __dict__ and not __slots__ is assumed
+// to be pickleable by default. Coroutine-wrappers have significant state so shouldn't be.
+// Therefore provide a default implementation
+static PyObject *__Pyx_CoroutineAwait_reduce_ex(__pyx_CoroutineAwaitObject *self, PyObject *arg) {
```
Comment (da-woods) [inline Cython/Utility/Coroutine.c:1508]: It turned out that by making it possible to lookup the class correctly, I inadvertently made it possible to pickle the class (which is correct, although likely to fail on unpickling since `_cython_VERSION_NUMBER` isn't a real module...), which inadvertently made it possible to pickle the instance (which is definitely incorrect). These were only impossible to pickle by luck before

File: Cython/Utility/CommonStructures.c [hunk 2]
```diff
@@ -125,36 +133,3 @@ static PyTypeObject *__Pyx_FetchCommonTypeFromSpec(PyObject *module, PyType_Spec
 }
 #endif
 
-
-/////////////// FetchCommonPointer.proto ///////////////
```
Comment (scoder) [inline Cython/Utility/CommonStructures.c:129]: I think removing this calls for a separate PR. (Specifically, reverting this PR for whatever potential future reason should not reinstate this code.)

File: Cython/Utility/Coroutine.c [hunk 3]
```diff
@@ -1501,13 +1501,31 @@ static PyObject *__Pyx_CoroutineAwait_no_new(PyTypeObject *type, PyObject *args,
 }
 #endif
 
+#if PY_VERSION_HEX < 0x03060000 || CYTHON_USE_TYPE_SPECS
+// In earlier versions of Python an object with no __dict__ and not __slots__ is assumed
+// to be pickleable by default. Coroutine-wrappers have significant state so shouldn't be.
+// Therefore provide a default implementation.
```
Comment (scoder) [inline Cython/Utility/Coroutine.c:1507]: This seems a separate PR as well. I understand that the name change unearthed this issue, but they are not actually otherwise related.

File: tests/run/common_utility_types.srctree [hunk 4]
```diff
@@ -36,3 +36,12 @@ assert type(a.funcA) is type(b.funcB)
 
 assert a.funcA.func_globals is a.__dict__
 assert b.funcB.func_globals is b.__dict__
+
+# Test that it's possible to look up the name of the class
+from sys import modules
+for n, mod in modules.items():
+    if n.startswith("_cython_"):  # the internal module..
```
Comment (scoder) [inline tests/run/common_utility_types.srctree:43]: Note that there might be more than one such module, e.g. when `numpy.random` is imported.

**Review by scoder — COMMENTED** [review]
Good catch. The `tp_name` is correct as being fully qualified, but the attribute name really shouldn't be.

**Comment by da-woods** [comment]
I've removed the 2 parts suggested to separate PRs. This PR will fail until #4381 is merged.

**Comment by da-woods** [comment]
Closing and re-opening just to run tests again now the coroutines patch is merged.

File: tests/run/common_utility_types.srctree (hunk 4 above)
Comment (da-woods) [reply tests/run/common_utility_types.srctree]: True - however, this is run in a srctree test that starts a separate process and imports almost nothing so I think it's safe. I've added an assert to confirm that.

I did try looking up `type(func).__module__` but that fails with type-specs because `__module__` is an accessor rather than a string. So I've reverted to a assuming there will only be one `_cython_` module.

**Comment by scoder** [comment]
Thanks!
