### PR TITLE
Handle platforms where sizeof(funcptr) != sizeof(void*)

### LINKED ISSUE #4683: [BUG] Possible issue storing function pointers in `__pyx_capi__`
**Describe the bug**

`__pyx_capi__` stores a bunch of function pointers in the `void*` field of `PyCapsule`. Standard C forbids casting a function pointer to a void pointer (although Posix requires it to work). To work around this Cython uses a union type-punning mechanism:

https://github.com/cython/cython/blob/617a9592726e5d779a1de2973c83f510e0d4c7d6/Cython/Utility/ImportExport.c#L579-L583

However, this doesn't really solve the problem: on some platforms (ia64 is a notable example I think) function pointers and regular pointers are different sizes, so the current method may lose information.

~I think this also affect memoryviews which also create capsules of function pointers.~ Edit: they aren't used for anything any more

I have a proposed fairly simple workaround in mind. I don't know how much we care, given there have been no real complaints about this.

**Additional context**

I was looking at this in the context of pickling CyFunctions (which also needs to stash a function pointer in a Python object at some point).

Numpy also looks to store function pointers in void pointers (in their import_array mechanism), looks to have had some support for ia64 at some point, and I can't find any bug reports about it. So I don't know if it's a real issue - I don't have a good way of testing it.

### PR DESCRIPTION
**Pull request by da-woods**
Fixes #4683

It's mostly a theoretical concern I think, but may apply to some "not too obscure" platforms (ia64?).

For the majority of platforms it keeps working as before (copies the function pointer into the void* of a capsule) although I've
used memcpy rather than a union to do this (because I don't believe the union trick is 100% guaranteed to work in standard
c++, although practically it does of course).

For any where this doesn't apply it allocates memory instead and the capsule points to that.

My interest in this is to use when pickling CyFunctions, but this PR just uses the mechanism for cimporting cdef functions

### CODE REVIEW

**Comment by da-woods** [comment]
Actually... this definitely won't work for pickling CyFunctions (since an arbitrary tuple isn't pickleable) so probably isn't worth trying to merge now as a bit of shared code.

I'll close this for now. If we get actually bug reports about the issue then it may be worth digging up again...

**Comment by scoder** [comment]
There seems to be a code style issue. Triggering a fresh build.

File: Cython/Utility/TypeConversion.c [hunk 1]
```diff
@@ -1137,3 +1137,55 @@ static CYTHON_INLINE {{TYPE}} {{FROM_PY_FUNCTION}}(PyObject *x) {
...
+static void __Pyx_destroy_c_func_ptr_capsule(PyObject *capsule) {
+    void* ptr = PyCapsule_GetPointer(capsule, PyCapsule_GetName(capsule));
+    free(ptr);
+}
+
+static PyObject *__Pyx_c_func_ptr_to_capsule(__Pyx_generic_func_pointer funcptr, const char* name) {
+    if (sizeof(funcptr) > sizeof(void*) || CYTHON_LARGE_FUNCTION_POINTERS) {
+        // The C standard does not guarantee that a function pointer fits inside a regular pointer
+        // (and on some platforms it doesn't). On these, we need to allocate space to store the function pointer
+        __Pyx_generic_func_pointer *copy_into = (__Pyx_generic_func_pointer*)malloc(sizeof(funcptr));
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:1162]: We should rather be using `PyMem_Malloc()` here, because why not let Python see what we do?
```suggestion
        __Pyx_generic_func_pointer *copy_into = (__Pyx_generic_func_pointer*) PyMem_Malloc(sizeof(funcptr));
```

File: Cython/Utility/TypeConversion.c [hunk 2]
```diff
@@ -1137,3 +1137,55 @@ static CYTHON_INLINE {{TYPE}} {{FROM_PY_FUNCTION}}(PyObject *x) {
...
+//@requires: CFuncPtrTypedef
+
+static PyObject *__Pyx_c_func_ptr_to_capsule(__Pyx_generic_func_pointer funcptr, const char* name); /* proto */
+
+/////////////// CFuncPtrToPy ///////////////
+//@requires: StringTools.c::IncludeStringH
+
+static void __Pyx_destroy_c_func_ptr_capsule(PyObject *capsule) {
+    void* ptr = PyCapsule_GetPointer(capsule, PyCapsule_GetName(capsule));
+    free(ptr);
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:1155]:
```suggestion
    PyMem_Free(ptr);
```

File: Cython/Utility/ModuleSetupCode.c [hunk 3]
```diff
@@ -391,6 +391,12 @@
 /* Whether to use METH_FASTCALL with a fake backported implementation of vectorcall */
 #define CYTHON_BACKPORT_VECTORCALL (CYTHON_METH_FASTCALL && PY_VERSION_HEX < 0x030800B1)
 
+#if !defined(CYTHON_LARGE_FUNCTION_POINTERS)
+// This can be defined to force an alternate code-path for testing purposes
+// There's no other reason to use it
+#define CYTHON_LARGE_FUNCTION_POINTERS 0
+#endif
```
Comment (scoder) [inline Cython/Utility/ModuleSetupCode.c:398]: If this is really only meant for testing, I'd rather not give it a public `CYTHON_*` name but an internal one, like `__Pyx_TEST_large_func_pointers` or so.

**Review by scoder — COMMENTED** [review]
Looks quite involved, but If it leads to safer C code, fine, why not.

File: Cython/Utility/TypeConversion.c [hunk 4]
```diff
@@ -1137,3 +1137,56 @@ static CYTHON_INLINE {{TYPE}} {{FROM_PY_FUNCTION}}(PyObject *x) {
...
+
+static __Pyx_generic_func_pointer __Pyx_capsule_to_c_func_ptr(PyObject *capsule, const char* name) {
+    void *data = PyCapsule_GetPointer(capsule, name);
+    __Pyx_generic_func_pointer result;
+    if (sizeof(__Pyx_generic_func_pointer) > sizeof(void*) || __Pyx_TEST_large_func_pointers) {
+        result = *((__Pyx_generic_func_pointer*)data);
+    } else {
+        memcpy((void*)&result, (void*)&data, sizeof(result));
+    }
+    return result;
```
Comment (scoder) [inline Cython/Utility/TypeConversion.c:1191]: Can it happen that `sizeof(result) < sizeof(data)`, so that the `memcpy()` writes to invalid memory?

Comment (da-woods) [reply Cython/Utility/TypeConversion.c:1191]: I think `sizeof(result)` can be less than `sizeof(data)`. But unless I'm missing something that isn't a problem here - it's writing into `result` so it won't write beyond the limits of `result`.

Comment (scoder) [reply Cython/Utility/TypeConversion.c:1191]: Hmm, right. It's difficult to get into the details here, also given byte ordering for differently sized pointer types and what not. But given that we use the same `memcpy` byte mapping in and out, it should be fine. Let's align the variable names in both functions to make this more clear.

```suggestion
    __Pyx_generic_func_pointer funcptr;
    if (sizeof(funcptr) > sizeof(void*) || __Pyx_TEST_large_func_pointers) {
        result = *((__Pyx_generic_func_pointer*)data);
    } else {
        memcpy((void*)&funcptr, (void*)&data, sizeof(funcptr));
    }
    return funcptr;
```

I'd actually rather expect function pointers to be smaller than data pointers (if they are different at all). Code is fairly unlikely to appear in masses similar to that of today's data.

**Review by scoder — APPROVED** [review]
