### PR TITLE
always consider 0-sized arrays as C- and F-contiguous

### LINKED ISSUE #2093: ValueError continuous memory view and 0-size numpy array
A ValueError is raised if one gives a numpy array with shape `(2, 0, 1)` to such Cython functions with a 3d memoryview as argument:

```cython
cimport numpy as np
import numpy as np
np.import_array()

cpdef myfunc3d(np.float64_t[:, :, ::1] arr):
    if arr.size > 0:
        print(arr[0, 0, 0])
    else:
        print('size == 0')
```

The code to get the error:

```python
import numpy as np
arr = np.ones((2, 0, 1))
print(arr.flags)
myfunc3d(arr)
```
which gives:
```
C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-81a397764d36> in <module>()
      1 arr = np.ones((2, 0, 1))
      2 print(arr.flags)
----> 3 myfunc3d(arr)

_cython_magic_5dfab2d7f2a0e837d79c56566c9147b4.pyx in _cython_magic_5dfab2d7f2a0e837d79c56566c9147b4.myfunc3d()

ValueError: Buffer and memoryview are not contiguous in the same dimension.
In [ ]:
```
Strangely, no error is raised for a shape `(1, 0, 1)`!

### PR DESCRIPTION
**Pull request by c-f-h**
fixes #2093

### CODE REVIEW

File: Cython/Utility/MemoryView_C.c [hunk 1]
```diff
@@ -347,18 +347,23 @@ static int __Pyx_ValidateAndInit_memviewslice(
...
     /* Check axes */
-    for (i = 0; i < ndim; i++) {
-        spec = axes_specs[i];
-        if (unlikely(!__pyx_check_strides(buf, i, ndim, spec)))
-            goto fail;
-        if (unlikely(!__pyx_check_suboffsets(buf, i, ndim, spec)))
+    if (buf->len > 0) {
+        /* 0-sized arrays do not undergo these checks since their strides are
+         * irrelevant and they are always both C- and F-contiguous
+         */
```
Comment (scoder) [inline Cython/Utility/MemoryView_C.c:353]: C-style multi-line comments are not discarded from the generated C file.
```suggestion
        // 0-sized arrays do not undergo these checks since their strides are
        // irrelevant and they are always both C- and F-contiguous.
```

File: tests/memoryview/relaxed_strides.pyx [hunk 2]
```diff
@@ -62,3 +62,14 @@ def test_zero_sized(array):
...
+
+def test_zero_sized_multidim(array):
+    """
+    >>> contig = np.ascontiguousarray(np.zeros((4,4,4))[::2, 2:2, ::2])
+    >>> _ = test_zero_sized_multidim(contig)
+
+    >>> a = np.zeros((4,4,4))[::2, 2:2, ::2]
+    >>> if NUMPY_HAS_RELAXED_STRIDES: _ = test_zero_sized_multidim(a)
+    """
+    cdef double[:, :, ::1] a = array
```
Comment (scoder) [inline tests/memoryview/relaxed_strides.pyx:74]: Can't we check f-contiguity here as well?

**Comment by c-f-h** [comment]
Thanks for the comments; all done.

**Comment by scoder** [comment]
Thanks
