### PR TITLE
Stop fallback indexing code using PySequence_*Item first

### LINKED ISSUE #5776: [BUG] Indexing self fails under PyPy with "%T index out of range"
### Describe the bug

I have a cdef class that has a `leading_coefficient` method:
```python
# polymod.pyx

cdef class poly:

    def __len__(self):
        return 0

    cpdef long degree(self):
        return -1

    def __getitem__(self, key):
        if key < 0:
            return 0

    def leading_coefficient(self):
        return self[self.degree()]
```
The `self.degree()` method can return `-1` but `__getitem__` can handle that case. The code runs fine under CPython but fails under PyPy with:
```python
>>>> p.leading_coefficient()
Traceback (most recent call last):
  File "/home/oscar/current/active/python-flint/tmp/cytest/stuff.py", line 7, in <module>
    print(p.leading_coefficient())
  File "polymod.pyx", line 14, in polymod.poly.leading_coefficient
    return self[self.degree()]
IndexError: %T index out of range
```
Calling `p[p.degree()]` with an instance of the class works fine but calling the `p.leading_coefficient()` method whose body is just `return self[self.degree()]` fails.

The bug is not seen if the `long` type declaration is removed or if the `degree` method is made `def`. The bug is still seen when degree is either `cpdef` or `cdef`. If the `__len__` method is removed then a different error is seen:
```python
Traceback (most recent call last):
  File "/home/oscar/current/active/python-flint/tmp/cytest/stuff.py", line 7, in <module>
    print(p.leading_coefficient())
  File "polymod.pyx", line 11, in polymod.poly.leading_coefficient
    return self[self.degree()]
TypeError: 'polymod.poly' has no length
```
Somehow the C code generated for `self[self.degree()]` is assuming that it can treat `self` as a sequence rather than using the `__getitem__` method that is defined. The code is basically:
```c
  /* "polymod.pyx":11
 * 
 *     def leading_coefficient(self):
 *         return self[self.degree()]             # <<<<<<<<<<<<<<
 */
...
 __pyx_t_2 = __Pyx_GetItemInt(((PyObject *)__pyx_v_self), __pyx_t_1, long, 1, __Pyx_PyInt_From_long, 0, 1, 1);
...
```
In turn this is defined as
```c
#define __Pyx_GetItemInt(o, i, type, is_signed, to_py_func, is_list, wraparound, boundscheck)\
    (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
    __Pyx_GetItemInt_Fast(o, (Py_ssize_t)i, is_list, wraparound, boundscheck) :\
    (is_list ? (PyErr_SetString(PyExc_IndexError, "list index out of range"), (PyObject*)NULL) :\
               __Pyx_GetItemInt_Generic(o, to_py_func(i))))
```
I'm not sure exactly which code paths are taken here.

I have tested with Cython 3.0.4 and also current Cython master under both CPython and PyPy and always this works under CPython and fails under PyPy.

### Code to reproduce the behaviour:

```cython
# polymod.pyx

cdef class poly:

    def __len__(self):
        return 0

    cpdef long degree(self):
        return -1

    def __getitem__(self, key):
        if key < 0:
            return 0

    def leading_coefficient(self):
        return self[self.degree()]
```
A script to test:
```python
# stuff.py

import polymod

p = polymod.poly()
print(p.degree())
print(p[-1])
print(p[p.degree()])
print(p.leading_coefficient())
```

### Expected behaviour

The `leading_coefficient` method should always return `0` and should not fail with an exception.

### OS

Linux

### Python version

PyPy 3.9-7.3.12

### Cython version

3.0.4 or current master

### Additional context

This comes from a python-flint issue:
https://github.com/flintlib/python-flint/issues/74#issuecomment-1773827740

### PR DESCRIPTION
**Pull request by da-woods**
since this behaves differently to the PyObject functions.

Fixes #5776 and some indexing bugs on PyPy and the Limited API

### CODE REVIEW

File: Cython/Utility/ObjectHandling.c [hunk 1]
```diff
@@ -465,7 +465,9 @@ static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Fast(PyObject *o, Py_ssize_t i,
         }
     }
 #else
-    if (is_list || PySequence_Check(o)) {
+    // PySequence_GetItem behaves differently to PyObject_GetItem for i<0
+    // and possibly some other cases so can't generally be substituted
+    if (is_list || PyList_CheckExact(o) || PyTuple_CheckExact(o)) {
```
Comment (da-woods) [inline Cython/Utility/ObjectHandling.c:470]: Here I've just made a fast path for `list` and `tuple`. I suspect it could be extended to include a few other builtin classes (`bytes`, `unicode`, `bytearray`, `memoryview`) but I didn't do that to keep the check simple.

Comment (scoder) [reply Cython/Utility/ObjectHandling.c:470]: Maybe like this?
```suggestion
    if (is_list || !PyMapping_Check(o)) {
```
The intention is to avoid the `int` object creation. If we assume (!) that checking for the protocol is faster than that, we win for sequences. But we'd pay with a double check for mappings. CPU-L1 caching might still keep that efficient in the end.

Note that this is all guessing. There are multiple settings in which this code will execute, PyPy, Limited API, user configurations in CPython, … I really cannot make a good guess for all of them, and guessing about performance is bound to go wrong anyway.

File: Cython/Utility/ObjectHandling.c [hunk 2]
```diff
@@ -534,11 +536,9 @@ static CYTHON_INLINE int __Pyx_SetItemInt_Fast(PyObject *o, Py_ssize_t i, PyObje
...
     }
 #else
-#if CYTHON_COMPILING_IN_PYPY
-    if (is_list || (PySequence_Check(o) && !PyDict_Check(o)))
-#else
-    if (is_list || PySequence_Check(o))
-#endif
+    // PySequence_SetItem behaves differently that PyObject_SetItem for i<0
+    // and possibly some other cases so can't generally be substituted
+    if (is_list || PyList_CheckExact(o) || PyTuple_CheckExact(o))
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c:541]:
```suggestion
    if (is_list || !PyMapping_Check(o))
```

File: Cython/Utility/ObjectHandling.c [hunk 3]
```diff
@@ -572,7 +572,9 @@ static int __Pyx_DelItem_Generic(PyObject *o, PyObject *j) {
 static CYTHON_INLINE int __Pyx_DelItemInt_Fast(PyObject *o, Py_ssize_t i,
                                                int is_list, CYTHON_NCP_UNUSED int wraparound) {
 #if !CYTHON_USE_TYPE_SLOTS
-    if (is_list || PySequence_Check(o)) {
+    // PySequence_DelItem behaves differently than PyObject_DelItem for i<0
+    // and possibly some other cases so can't generally be substituted
+    if (is_list || PyList_CheckExact(o) || PyTuple_CheckExact(o)) {
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c:577]:
```suggestion
    if (is_list || !PyMapping_Check(o)) {
```

**Review by scoder — COMMENTED** [review]
I'll just change it and see what happens. It's definitely more correct than what we had before.

**Comment by da-woods** [comment]
I've fixed up the wording to be consistent. I think `PyMapping_Check` is probably the right check here although as you say, it's probably futile trying to guess the performance implications for all cases.

File: Cython/Utility/ObjectHandling.c [hunk 4]
```diff
@@ -465,7 +465,9 @@ static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Fast(PyObject *o, Py_ssize_t i,
         }
     }
 #else
-    if (is_list || PySequence_Check(o)) {
+    // PySequence_GetItem behaves differently to PyObject_GetItem for i<0
+    // and possibly some other cases so can't generally be substituted
+    if (is_list || !PyMapping_Check(o)) {
         return PySequence_GetItem(o, i);
```
Comment (oscarbenjamin) [inline Cython/Utility/ObjectHandling.c:471]: Can either of `PyMapping_Check` or `PySequence_Check` really be depended on for this?

The Cython class from the issue is:
```cython
cdef class poly:

    def __len__(self):
        return 0

    cpdef long degree(self):
        return -1

    def __getitem__(self, key):
        if key < 0:
            return 0

    def leading_coefficient(self):
        return self[self.degree()]

poly().leading_coefficient()
```
This class conforms to neither of the mapping or sequence protocols. Does Cython generate `tp_as_mapping` for a type like this?

I would have expected `PyMapping_Check` to return false in this case:
https://github.com/python/cpython/blob/1198076447f35b19a9173866ccb9839f3bcf3f17/Objects/abstract.c#L2358-L2363

The change here looks as if it would still use `PySequence_GetItem` for this type unless I misunderstand it.

Comment (oscarbenjamin) [reply Cython/Utility/ObjectHandling.c:471]: Actually it looks like `PyMapping_Check` and `PySequence_Check` both return `True` in this case.

Comment (oscarbenjamin) [reply Cython/Utility/ObjectHandling.c:471]: For a Cython type it looks like `PyMapping_Check` will give true any time `__getitem__` is defined:
```cython
from cpython cimport PyMapping_Check

cdef class poly:

    def __getitem__(self, key):
        pass

    def check(self):
        return PyMapping_Check(self)
```

Comment (oscarbenjamin) [reply Cython/Utility/ObjectHandling.c:471]: When would it ever be safe to use `PySequence_GetItem` if you don't know explicitly that the object is a concrete sequence type like list or tuple?

**Comment by oscarbenjamin** [comment]
> We have to call either PyMapping_GetItem() or PySequence_GetItem(), so if it's not the one, we call the other.

Okay, I see. The alternative fallback is to call `PyObject_GetItem` which would only try `tp_as_mapping` before again calling `PySequence_GetItem`. So if `PyMapping_Check` is false then we can cut straight to `PySequence_GetItem` to skip out converting the C integer to a Python integer and back.

File: tests/run/index.pyx [hunk 5]
```diff
@@ -335,3 +339,33 @@ def set_large_index(obj, Py_ssize_t index):
...
+            raise RuntimeError("Positive index")
+
+    def __len__(self):
+        return 500
+
+def test_call_with_negative_numbers():
+    """
+    The key point is that Cython shouldn't default to PySequence_*Item
+    since that invisibly adjusts negative numbers to be len(o)-idx.
+    >>>
```
Comment (scoder) [inline tests/run/index.pyx:365]:
```suggestion
    >>> test_call_with_negative_numbers()
    'Good'
```
