### PR TITLE
Fix bound class methods when unpacking builtin method calls

### LINKED ISSUE #5051: [BUG] When using the dictionary fromkeys method in a class, the converted C source code crashes on execution
### Describe the bug

When using the dictionary fromkeys method in a class, the converted C source code crashes on execution

### Code to reproduce the behaviour:

```cython
# example code
class LsaLsdb(object):
    def __init__(self):
        pass

    def test(self):
        new_node = {}
        new_node['area-id'] = ['0.0.0.0', '0.0.0.0']
        test_dict = {}
        new_node['area-id'] = test_dict.fromkeys(new_node['area-id']).keys()
        print(new_node['area-id'])


lsa = LsaLsdb()

lsa.test()
```
```bash
cython -2  --embed -o test.c test.py
gcc -g -I /usr/include/python2.7 test.c -lpython2.7 -o test

run test, and Segmentation fault
```

### Expected behaviour

['0.0.0.0']

### Environment

OS: Linux
Python version 2.7.17
Cython version 3.0.0a11 and 0.29.32

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0dminnimda**
Enhance #5075 - use c api insted of evaluating python code

From #5075
> The general optimization for unpacking builtin method calls was breaking bound classmethods (with crashes on Py2 and wrong answers on Py3).
> 
> This PR adds code to handle it. The code is unlikely to be very fast, but my judgement is that this is a rare case and thus it's more important just to get it to work rather than to optimize this case.
> 
> Fixes #5051

### CODE REVIEW

**Comment by mattip** [comment]
Interesting, I wonder if the [pypy 3.9 job](https://github.com/cython/cython/actions/runs/3958008677/jobs/6779062036) will pass this test. I seem to recall I only partially implemented PyCFunction.

**Comment by 0dminnimda** [comment]
Based on actions that were run in my fork everyting passes
https://github.com/0dminnimda/cython/actions/runs/3957861284/jobs/6778749335

**Comment by 0dminnimda** [comment]
There were some warnings though
```
warning: missing initializer for field ‘tp_pypy_flags’ of ‘PyTypeObject’ {aka ‘struct _typeobject’} [-Wmissing-field-initializers]
```
but as it seems they have nothing to do with PyCFunction

**Comment by 0dminnimda** [comment]
Thing is that the new PyCFunction is not going to be accessible to python code, it's more like a delayed function call with some arguments memorised

File: Cython/Utility/ObjectHandling.c [hunk 1]
```diff
@@ -2000,15 +2019,53 @@ static int __Pyx_TryUnpackUnboundCMethod(__Pyx_CachedCFunction* target) {
...
+#if CYTHON_COMPILING_IN_LIMITED_API || CYTHON_COMPILING_IN_PYPY
+        Py_XDECREF(self);
+#endif
+        if (self_found) {
+            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
+            if (unlikely(!unbound_method)) {
+                Py_DECREF(method);
+                return -1;
+            }
+            Py_INCREF(method);  // PyCFunction will Py_XDECREF method on destruction
```
Comment (0dminnimda) [inline Cython/Utility/ObjectHandling.c:2065]: If I think about it it seems wrong, `__Pyx_PyObject_GetAttrStr` should have already incremented the refcount so we should be fine then?

File: Cython/Utility/ObjectHandling.c [hunk 2]
```diff
@@ -1992,6 +1992,25 @@ typedef struct {
 /////////////// UnpackUnboundCMethod ///////////////
 //@requires: PyObjectGetAttrStr
 
+#define CONST_REINTERPRET_CAST(pointer_type, pointer) ((pointer_type)(void *)(pointer))
```
Comment (da-woods) [inline Cython/Utility/ObjectHandling.c:1995]: I don't think function pointer->void* is actually portable. I believe function pointer-> other function pointer is allowed though.

Also, if we want to keep these they should probably have `__PYX_` names

File: Cython/Utility/ObjectHandling.c (hunk 1 above)
Comment (da-woods) [reply Cython/Utility/ObjectHandling.c:2065]: `PyCFunction_New` increfs self internally, so it `XDECREF`s its own reference. We want to `Py_DECREF` method on both the error and non-error path after `PyCFunction_New` I think

Comment (0dminnimda) [reply Cython/Utility/ObjectHandling.c:2065]: Oh yeah, I missed that `Py_XNewRef` for self.
I think you are correct, previosly `method` was not cleaned up on a non-error path

This maked me think if we can have some test on how much memory is still occupied before python terminates, it would be nice to catch those kinds of errors, this is likely to be a systematic problem

Also I wonder if there is a valgrind test, it still seems like a good idea to have it at least for one platform

Comment (da-woods) [reply Cython/Utility/ObjectHandling.c:2065]: I don't think Python cleans up after itself perfectly on shutdown anyway so I believe Valgrind is quite hard to interpret.

We have refnanny for references in generated code, but not utility code.

File: Cython/Utility/ObjectHandling.c (hunk 2 above)
Comment (da-woods) [reply Cython/Utility/ObjectHandling.c:1995]: > > Also, if we want to keep these they should probably have __PYX_ names

> Sure! I can see some areas that can benifit from clean up with those macros, if I want to refactor them it should probably be done in another pr

For now I'm just suggesting changing changing the name to not clash with anything a user/library might have defined. I agree a refactor of elsewhere shouldn't be in this PR

File: Cython/Utility/ObjectHandling.c [hunk 3]
```diff
@@ -2000,15 +2020,54 @@ static int __Pyx_TryUnpackUnboundCMethod(__Pyx_CachedCFunction* target) {
...
+            // PyCFunction_New will create and own method reference, no need to worry about it
+            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
+            if (unlikely(!unbound_method)) {
+                Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
+                return -1;
+            }
+            target->method = unbound_method;
+        }
+    }
+    Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
```
Comment (da-woods) [inline Cython/Utility/ObjectHandling.c:2070]:
```suggestion
            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
            Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
            if (unlikely(!unbound_method)) {
                return -1;
            }
            target->method = unbound_method;
        }
    }
```

So I think we only want to decref method in the classmethod case. In the normal non-classmethod case where we've just set `target->method = method` then I don't think it should be decrefed.

File: Cython/Utility/ObjectHandling.c [hunk 4]
```diff
@@ -2000,15 +2020,53 @@ static int __Pyx_TryUnpackUnboundCMethod(__Pyx_CachedCFunction* target) {
...
+        self = PyCFunction_GET_SELF(method);
+#endif
+        self_found = (self && self != Py_None);
+#if CYTHON_COMPILING_IN_LIMITED_API || CYTHON_COMPILING_IN_PYPY
+        Py_XDECREF(self);
+#endif
+        if (self_found) {
+            // PyCFunction_New will create and own method reference, no need to worry about it
+            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
+            Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
```
Comment (0dminnimda) [inline Cython/Utility/ObjectHandling.c:2063]:
```suggestion
            // New PyCFunction will own method reference
            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
            Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
```

File: Cython/Utility/ObjectHandling.c [hunk 5]
```diff
@@ -2000,15 +2020,53 @@ static int __Pyx_TryUnpackUnboundCMethod(__Pyx_CachedCFunction* target) {
...
+#if CYTHON_COMPILING_IN_LIMITED_API || CYTHON_COMPILING_IN_PYPY
+        Py_XDECREF(self);
+#endif
+        if (self_found) {
+            // New PyCFunction will own method reference
+            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
+            Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
+            if (unlikely(!unbound_method)) {
+                return -1;
+            }
```
Comment (0dminnimda) [inline Cython/Utility/ObjectHandling.c:2066]:
```suggestion
            if (unlikely(!unbound_method)) return -1;
```

File: Cython/Utility/ObjectHandling.c [hunk 6]
```diff
@@ -2000,15 +2020,51 @@ static int __Pyx_TryUnpackUnboundCMethod(__Pyx_CachedCFunction* target) {
...
+#endif
+        self_found = (self && self != Py_None);
+#if CYTHON_COMPILING_IN_LIMITED_API || CYTHON_COMPILING_IN_PYPY
+        Py_XDECREF(self);
+#endif
+        if (self_found) {
+            // New PyCFunction will own method reference
+            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
+            Py_DECREF(method);  // __Pyx_PyObject_GetAttrStr
+            if (unlikely(!unbound_method)) return -1;
```
Comment (0dminnimda) [inline Cython/Utility/ObjectHandling.c:2064]:
```suggestion
            PyObject *unbound_method = PyCFunction_New(&__Pyx_UnboundCMethod_Def, method);
            if (unlikely(!unbound_method)) return -1;
            // New PyCFunction will own method reference, thus decref __Pyx_PyObject_GetAttrStr
            Py_DECREF(method);
```

**Comment by da-woods** [comment]
This is definitely an improvement on what I was doing an now looks right to me. I won't merge it because I'm not really an "independent reviewer" here.

The whole thing is a bit of a messy workaround, but it's covering such an obscure corner case that I think that's fine.

File: Cython/Utility/ObjectHandling.c (hunk 1 above)
Comment (0dminnimda) [reply Cython/Utility/ObjectHandling.c]: I tried to experiment with [cpython/Misc/Readme.valgrind](https://github.com/python/cpython/blob/main/Misc/README.valgrind) and [cpython/Misc/valgrind-python.supp](https://github.com/python/cpython/blob/main/Misc/valgrind-python.supp), but it's not very fruitful 
I tried to generate a suppression from the scratch, and I'm getting mixed results

Comment (0dminnimda) [reply Cython/Utility/ObjectHandling.c]: Actually this should be a separate issue

File: Cython/Utility/ObjectHandling.c [hunk 7]
```diff
@@ -1992,6 +1992,26 @@ typedef struct {
 /////////////// UnpackUnboundCMethod ///////////////
 //@requires: PyObjectGetAttrStr
 
+#define __PYX_REINTERPRET_FUNCION(func_pointer, other_pointer) ((func_pointer)(void(*)(void))(other_pointer))
+#define __PYX_REINTERPRET_POINTER(pointer_type, pointer) ((pointer_type)(void *)(pointer))
+#define __PYX_RUNTIME_REINTERPRET(type, var) (*(type *)(&var))
+
+static PyObject *__Pyx_SelflessCall(PyObject *method, PyObject *args, PyObject *kwargs) {
+    PyObject *selfless_args = PyTuple_GetSlice(args, 1, PyTuple_Size(args));
```
Comment (0dminnimda) [inline Cython/Utility/ObjectHandling.c:2000]: Do I need to use cython versions of those, if they exist (I didn't really check)?

Comment (da-woods) [reply Cython/Utility/ObjectHandling.c:2000]: No, I don't think so - they're straight-forward and universally available so there's nothing for Cython to wrap.

File: Cython/Utility/ObjectHandling.c (hunk 1 above)
Comment (scoder) [reply Cython/Utility/ObjectHandling.c]: > We have refnanny for references in generated code, but not utility code.

Note that you can use it also in utility code, if you put in the required declarations and use the refnanny incref/decref/gotref/giveref macros. We just don't normally do it because it's cumbersome to copy all the boiler plate code together and write refnanny code by hand. If it helps here, it might be worth using. (My guess is that there are quite a number of utility code functions that might benefit from this, especially in `ObjectHandling.c` and `Builtins.c`, which deal a lot with object references.

File: Cython/Utility/ObjectHandling.c (hunk 7 above)
Comment (scoder) [inline Cython/Utility/ObjectHandling.c:2000]: Seems worth using a vectorcall here, if available, rather than creating a new tuple just for the call. (Not sure if that's an optimisation that we need to do right now.)

File: Cython/Utility/ObjectHandling.c [hunk 8]
```diff
@@ -2000,15 +2020,51 @@ static int __Pyx_TryUnpackUnboundCMethod(__Pyx_CachedCFunction* target) {
     target->method = method;
 #if CYTHON_COMPILING_IN_CPYTHON
     #if PY_MAJOR_VERSION >= 3
-    // method descriptor type isn't exported in Py2.x, cannot easily check the type there
     if (likely(__Pyx_TypeCheck(method, &PyMethodDescr_Type)))
+    #else
+    // method descriptor type isn't exported in Py2.x, cannot easily check the type there.
+    // Therefore, reverse the check to the most likely alternative
+    // (which is returned for class methods)
+    if (likely(!PyCFunction_Check(method)))
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c:2028]: There is some code that already handles this case in the `ClassMethod` section of `CythonFunction.c`. Could be extracted into a reusable `__Pyx_PyMethodDescr_Check()` function (which PyPy supports already).

File: Cython/Utility/ObjectHandling.c [hunk 9]
```diff
@@ -1992,6 +1992,26 @@ typedef struct {
 /////////////// UnpackUnboundCMethod ///////////////
 //@requires: PyObjectGetAttrStr
 
+#define __PYX_REINTERPRET_FUNCION(func_pointer, other_pointer) ((func_pointer)(void(*)(void))(other_pointer))
+#define __PYX_REINTERPRET_POINTER(pointer_type, pointer) ((pointer_type)(void *)(pointer))
+#define __PYX_RUNTIME_REINTERPRET(type, var) (*(type *)(&var))
```
Comment (scoder) [inline Cython/Utility/ObjectHandling.c:1997]: You seem to be using only the first of these three. We shouldn't commit unused code. It's really nice to know about these, though. We could add them to `ModuleSetupCode.c` instead and comment them out with `//`, so that the unused ones don't take any space in the generated C files, but are still available if they start becoming useful. (There are probably places already where they could be applied.)

**Review by scoder — COMMENTED** [review]
Looks good to me as well. Remember to change the commit comment on merge.

File: Cython/Utility/ObjectHandling.c (hunk 7 above)
Comment (da-woods) [reply Cython/Utility/ObjectHandling.c:2000]: This is definitely an obscure corner case so I'd be inclined to keep it simple for now. Much as this feels like a place that vectorcall would be good for

File: Cython/Utility/ObjectHandling.c (hunk 1 above)
Comment (0dminnimda) [reply Cython/Utility/ObjectHandling.c]: resolving in favor of #5224

File: Cython/Utility/ObjectHandling.c (hunk 7 above)
Comment (0dminnimda) [reply Cython/Utility/ObjectHandling.c]: I added a comment with such a note, I think it's sufficient right now

File: Cython/Utility/ObjectHandling.c (hunk 8 above)
Comment (0dminnimda) [reply Cython/Utility/ObjectHandling.c:2025]: IMHO, this fix deserves it's own pr (#5225), it's scope is different from what this pr tries to solve

**Comment by 0dminnimda** [comment]
Ok, now it's good to go, I think

File: Cython/Utility/ModuleSetupCode.c [hunk 10]
```diff
@@ -541,6 +541,13 @@
   #endif
 #endif
 
+// reinterpret
+
+// TODO: refactor existing code to use those macros
+#define __PYX_REINTERPRET_FUNCION(func_pointer, other_pointer) ((func_pointer)(void(*)(void))(other_pointer))
+// #define __PYX_REINTERPRET_POINTER(pointer_type, pointer) ((pointer_type)(void *)(pointer))
+// #define __PYX_RUNTIME_REINTERPRET(type, var) (*(type *)(&var))
+
```
Comment (scoder) [inline Cython/Utility/ModuleSetupCode.c:550]:
```suggestion


```
